### ISSUE TITLE
PS3NETSERV // PSXISO Folder Performance

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#103]
Not sure if this is an issue or intentional but the PS1 ROMS that I have got stored here \\retrosmb\retronas\roms\sony\playstation1 are not appearing in the PS3NETSRV PSXISO Folder. Is there anyway to make that work?

**Comment by sairuk** [comment]
Took a look a the playbook and they should be in a subfolder called `iso` that should be symlinked to `PSXISO`

```
- { src: "../../roms/sony/playstation1/iso", dest: "PSXISO" }
```

**Comment by davedoc1984** [comment]
Yes thanks that worked. However its incredibly slow when trying to browse to it using mmCm.

I use Ethernet for both the RetroNAS and the PS3.

Also, is there anyway for WebMan MOD to pick up the fact I have the NAS and access the games from there? I couldn't see any easy way to set this up. Only Net mounting to dev/bdvd which won't work.

**Comment by danmons** [comment]
> Yes thanks that worked. However its incredibly slow when trying to browse to it using mmCm.

Can you elaborate? What speeds are you seeing.  The video in the wiki shows the speeds I was getting, and these could get up to around 400mbit/s (40MB/s), which I think was limited by my PS3's internal HDD.


> Also, is there anyway for WebMan MOD to pick up the fact I have the NAS and access the games from there? I couldn't see any easy way to set this up. Only Net mounting to dev/bdvd which won't work.

Also in the video in the wiki, I document in webMAN-MOD how to put in a network path.  Is this not working for PS1 content for you?

**Comment by davedoc1984** [comment]
@danmons Followed your excellent guidance on WebMan MOD and its all sorted now. Picks up my Games and shows them as Net games :) Also it seems to work well.

mmCm was where I was trying to do everything and when asking it to look over the network for content it was taking a while (PS1, PS2, PSP etc) but I am not worried about that now that WebMan MOD is working which is much better for me to use.
