### ISSUE TITLE
Error creating folders

### ISSUE THREAD

**Issue by lilylarceny** [danmons/retronas#105]
I thought this error was related to Symlink, however it seems to be something with the fact that I have changed my top level directory?

![retronas GC error](https://user-images.githubusercontent.com/100004188/154809532-59941146-4473-4e49-9c43-2f78c3a5b0ad.png)
![retronas xbox error](https://user-images.githubusercontent.com/100004188/154809642-934a4ce7-0db4-420b-ac6b-9805437c85d7.JPG)

**Comment by danmons** [comment]
When you changed your top level dir, dir you set the new path in the "Global configuration" section?

**Comment by lilylarceny** [comment]
Yes, and I updated the directory before I installed anything.

**Comment by danmons** [comment]
Apologies, it was an error on our end.  The right folders/links are now in the new systems module.

If you exit right out of the RetroNAS system, and fire it back up again from the TUI, the new code will come down and work for FSP.

I'm checking the Xbox360 item now in the other issue, will respond there when I've confirmed that's working again.

**Comment by sairuk** [comment]
@lilylarceny have you had a chance to test these changes?

**Comment by lilylarceny** [comment]
I did, yes, it appears to be fixed now.

**Comment by sairuk** [comment]
Thank you I will continue with closure of this issue
