### ISSUE TITLE
PS3 WebMan Mod only seeing PS2 DVD games and not CD (works on a Real PS2 with OPL just fine)

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#109]
I have managed to get my PS3 with WebMan MOD to successfully see my content for PS3, PS2 and PSX games.

However, I have noticed that its only pulling through the PS2 DVD-ROM ISOs and not any of the CD-ROM ISOs.

**Comment by danmons** [comment]
Bit of a challenge here.  We split out PS2 games into DVD and CD dirs/links for OpenPS2Loader on PS2. 

In ps3netsrv we only have a "PS2ISO" option, which I've linked to the DVD folder for PS2. 

What I can do is try linking one level up to the PS2 level, however I don't know if ps3netsrv is happy with subdirs.  I don't have a way to test, so I'll commit the code and ask for some feedback on this if possible.  I'll update again when the change is made.

**Comment by davedoc1984** [comment]
No @danmons  worries happy to be your tester for this.

**Comment by danmons** [comment]
I've changed the symlink location for the PS2ISO folder.  You'll need to delete/rename the existing symlink and re-run the ps3netsrv installer from RetroNAS for it to correctly install the new one.

**Comment by davedoc1984** [comment]
@danmons where do I find the symlink to remove it?

**Comment by danmons** [comment]
> @danmons where do I find the symlink to remove it?

You can either use the command line or the cockpit file manager.

The symlink is under your RetroNAS top level dir, under `ps3/ps3netsrv`. It's called "PS2ISO".  Simply rename that to "PS2ISO.old" and re-run the ps3netsrv installer.

**Comment by s3anami** [comment]
The webman mod doesn't like the folder structure for this for me, but its fine for multiman itself. It seems to crash easily on a lot of items too but that's not a retronas issue.

**Comment by s3anami** [comment]
i got them to fix folder support in webman, however it only supports single letters and no special chars
If  its possible for you to make a symlink to a folder with a single letter as a name it will work properly.
For example cd folder to c folder in ps3net folder and dvd to d folder

**Comment by sairuk** [comment]
Linking to the WebmanMOD ticket for reference https://github.com/aldostools/webMAN-MOD/issues/642

**Comment by s3anami** [comment]
yes it works, are you on the latest webman from last week?
https://imgur.com/a/aTgLWUj

**Comment by sairuk** [comment]
I recompiled ps3netsrv 20220326 this morning and am on webmanmod 1.47.38 with HEN 3.0.3

capitalization also makes no difference for me

**Comment by s3anami** [comment]
not sure then, it works for me as the images show. Webman doesn't display the folders just the items within the folders for me correctly if that's your issue.
Meaning retronas puts out a b c or whatever folder and webman just lists the contents within not the folders

**Comment by sairuk** [comment]
Grabbed the latest version of 1.47.38 and the hash was different to the one I had so reinstalled webMAN, but behaviour is still the same

Until this has stabilised RetroNAS wont be making any further changes.

**Comment by s3anami** [comment]
you should open a new issue since i doubt he will see a closed issue and I cannot reopen it since he closed it himself

**Comment by sairuk** [comment]
we're not going to be doing anything in this space with RetroNAS, there some weirdness with my install of webMAN MOD that i'll work through with the main project but i'm closing this off because the moving of the symlink is fine for others.
