### ISSUE TITLE
Scripts not accessible

### ISSUE THREAD

**Issue by eb0687** [danmons/retronas#115]
I get the below when clicking the Scripts section in retronas:

![Dimmer_n3b4nVU7c6](https://user-images.githubusercontent.com/20299245/155116253-8a76e042-808e-415a-a877-99f358cb5052.png)

Then it goes back to the main menu, I cant access any of the scripts unfortunately, must have something to do with today's update? because It was working fine yesterday.

Also, where are the scripts located exactly in the filesystem? running debian btw..

**Comment by eb0687** [comment]
Other sections seem to be fine, its just this section where I get the error..

**Comment by sairuk** [comment]
yeh seems to be a problem with todays update, i will take a look shortly

**Comment by sairuk** [comment]
I have just committed https://github.com/danmons/retronas/commit/b112263f0896ba9a79729353592229da9294ff1d which should address the issue thanks for letting us know about it

**Comment by eb0687** [comment]
great! thanks for the prompt action and glad to be of assistance!

closing, issue resolved.
