### ISSUE TITLE
Trouble recreating symlinks for ROM folders

### ISSUE THREAD

**Issue by citizen-why** [danmons/retronas#116]
Due to the way i copied over my rom folders I ended up with the symlinks for roms/nintentdo/famicom_disk and roms/nintendo/nes having the wrong ownership and permissions. I deleted the symlinks (confirming that the direcotires they pointed to are still there) and reran the Samba for MISTer script in the TUI but the symlinks did not get re-created.

Any idea how to correct this?

**Comment by sairuk** [comment]
I am not sure I understand exactly the problem. Do you mean the folder have permissions that differ from expected? This should have been repaired as you rerun the playbook for MiSTer.

* `roms/nintendo/nes` should not be a folder, it should be a symlink
* `roms/nintendo/famicom_disk` i believe was something we identified as currently missing recently and needs correction.

Could you please clarify if all other symlinks created correctly for MiSTer?

**Comment by citizen-why** [comment]
Sorry for the confusion. 

Due to the way I migrated my collection - I ended up messing up the permissions and had The following symlinks showing as having the wrong ownership and permission:
    roms/nintendo/nes --> roms/nintendo/famicom
    roms/nintendo/famicom_disk --> roms/nintendo/famicom

I'm fairly confident that roms/nintentdo/nes was a symlink pointing to roms/nintendo/famicom, and roms/nintendo/famicom_disk was also a symlink pointing to roms/nintendo/famicom but maybe I'm mistaken?


Eitherway, here were the steps I followed to correct this
1.) I deleted the symlinks expecting them to be regenerated when I ran the Samba for Mister option in the TUI. 
2.) Confirmed that the target directory roms/nintendo/famicom exists with the right permissions (owned by my default user "retronas_user"
3.) Opened retronas and ran the Samba for Mister option from install things

Unfortunately, I ran that script, but the deleted items have not been regenerated and are still deleted
![image](https://user-images.githubusercontent.com/99519679/155250474-b2825d74-454a-443f-9366-5627a9329125.png)
![image](https://user-images.githubusercontent.com/99519679/155250578-88894a03-7265-468b-bf8e-9aaafed28fa4.png)

Is there a particular step I need to take to rerun the playbook beyond what I have done?

**Comment by citizen-why** [comment]
And disregard - after running it 4 times earlier today with no success, I just reran it again and the following symlinks regenerated:
roms/nintendo/nes --> roms/nintendo/famicom
roms/nintendo/snes --> roms/nintendo/superfamicom

Not sure why it didn't work earlier today and just worked now... but its resolved

![image](https://user-images.githubusercontent.com/99519679/155251365-b0651aaa-e5ba-4845-9a3d-bfaea3b5fc25.png)

**Comment by sairuk** [comment]
sorry i had no chance to come back around to this yet, the message you saw said you could now run `retronas` at the cli instead of the long `sudo /opt/retronas/retronas.sh`

we have made no changes that space I am aware of so it is certainly odd, i will close thise for now and we can revisit if have more reports of the same.

thanks for the follow up
