### ISSUE TITLE
PS3 Help 

### ISSUE THREAD

**Issue by SammyC65** [danmons/retronas#118]
I have made a couple of ISO with my own Ps3 games they rip ok to PS3 folder on Retronas Folders but can't seem to play the games 
Error seem to get is 
1: ISO Type: 32 
2: ISO Path (i) [/net_host0/PS3ISO/My Game ISO
3: ISO Path (0)
4: ISO Segs: 1
5: Error: 80010002 (Einval)

**Comment by sairuk** [comment]
There is an existing conversation [here](https://github.com/danmons/retronas/issues/48) about bad permissions on games ripped, please add your information there so we can keep it in one place
