### ISSUE TITLE
[wiki] MiSTer optional cifs mount line in guide leads to 'No Files' on MiSTER

### ISSUE THREAD

**Issue by jnackmclain** [danmons/retronas#119]
In the wiki, there is a bit mentioning an optional line in the script.

"Optionally you may add an additional option to the cifs_mount.ini file to minimise the amount you need to navigate to load games

LOCAL_DIR="games""

Having this line in my cifs ini caused the core, at least GBA in my testing, display "No Files"
Once I took out this line and rebooted, the problem went away and I can load the games.
This is my first time using MiSTer admittedly, and all I've done is the initial update_all.sh.
Otherwise looking good thank you!

**Comment by sairuk** [comment]
Yes you are correct, with the changes that came out of issue https://github.com/danmons/retronas/issues/21 this configuration is now redundant and should have been removed, I have now made the change. Thanks for letting us know.
