### ISSUE TITLE
Lighttpd installation error

### ISSUE THREAD

**Issue by eb0687** [danmons/retronas#12]
I am unable to install Nintendo 3DS QR code generator for FBI Homebrew, when running journalctl -xe I get the below ouput, any ideas on how to fix this?

I tried installing lighttpd on its own, but same issue unfortunately.

```
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit lighttpd.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Feb 01 20:06:41 retronas systemd[1]: Stopped Lighttpd Daemon.
-- Subject: A stop job for unit lighttpd.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit lighttpd.service has finished.
--
-- The job identifier is 4027 and the job result is done.
Feb 01 20:06:41 retronas systemd[1]: lighttpd.service: Start request repeated too quickly.
Feb 01 20:06:41 retronas systemd[1]: lighttpd.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit lighttpd.service has entered the 'failed' state with result 'exit-code'.
Feb 01 20:06:41 retronas systemd[1]: Failed to start Lighttpd Daemon.
-- Subject: A start job for unit lighttpd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit lighttpd.service has finished with a failure.
```

**Comment by eb0687** [comment]
Oh I forgot to mention, I am running retronas on a ubuntu server 20.04 inside a proxmox vm.

**Comment by birdybro** [comment]
Ubuntu 20.04 is not currently supported, there are lots of different versions. Additionally, proxmox limits access of the pseudo-vm to the whole kernel for security purposes, so there may be some significant hurdles in the way.

https://pve.proxmox.com/wiki/Linux_Container
```
For security reasons, access to host resources needs to be restricted. Therefore, containers run in their own separate namespaces. Additionally some syscalls (user space requests to the Linux kernel) are not allowed within containers.
```

**Comment by eb0687** [comment]
I will give debian a try. 
Yes I am aware of the LXC limitations and installed ubuntu on a vm instead.

Will post back here with my results, maybe in a couple of hours or so.

**Comment by danmons** [comment]
Long term goal is to support more distros, however that's a lot to take on right now with the amount of interest in the project.

The Ansible engine that drives RetroNAS is capable of being distro-aware, but I still have to configure and test everything on multiple platforms.  So yes, unfortunately for now Debian 11 is the target, mostly because that's what Raspberry Pi OS is based on, and it's a pretty compatible/stable distro with lots of old-ish hardware and VM platforms.

**Comment by birdybro** [comment]
Yup, everything I threw at Debian 11 in a Hyper-V VM worked perfectly, so you've done a good job on that. Thanks!

**Comment by eb0687** [comment]
I can confirm that the issues were resolved when installing on Debian 11. 

Thanks for the help. 
This can be marked as resolved.
