### ISSUE TITLE
permissions errors and changing the storage to NFS

### ISSUE THREAD

**Issue by tanuki2k** [danmons/retronas#127]
I used cockpit to set the storage to a NFS on my synology NAS.  i then used RetroNAS to set the data der to the same mount point. However when ever I try to install stuff I get an error similar to this:

failed: [localhost] (item=gog) => {"ansible_loop_var": "item", "changed": false, "gid": 100, "group": "users", "item": "gog", "mode": "0777", "msg": "chown failed: [Errno 1] Operation not permitted: b'/data/retronas/gog'", "owner": "1024", "path": "/data/retronas/gog", "size": 0, "state": "directory", "uid": 1024}

Looks to me like a permission issues? Thus I set RetroNAS to use root as the user but that didn't seem to fix thing ever.

**Comment by sairuk** [comment]
you'll need to make sure the NFS export options permit chown and you are running RetroNAS as a user who can issue changes to ownership 

e.g. run RetroNAS as root and set the appropriate non-root RetroNAS user in the Global Configuration

**Comment by the0remora** [comment]
The default UserID for the first synology user is 1026. I use NFS to my Linux installs and always have to change my ID to 1026. However adding your retronas user to Group 1026, 100, and 101 should take care of 90% of the issues.

I can add commands to this if anyone needs them but changing the UID has to be done from a second account.

**Comment by danmons** [comment]
> The default UserID for the first synology user is 1026. I use NFS to my Linux installs and always have to change my UID to 1026. However adding your retronas user to Group 1026, 100, and 101 should take care of 90% of the issues.
> 
> I can add commands to this if anyone needs them but changing the UID has to be done from a second account.

Good information, thank you.

Adding groups / GIDs to an existing user account can be done in Cockpit (logging in as the root user).

**Comment by jamescadd** [comment]
I'm trying to install the PS2 stuff using TrueNAS as the backend and having similar issues.  The TrueNAS user/group have the same name and ID values as the RetroNAS user, but I'm still getting errors about chown permissions failures.  I've tried a number of configurations of permissions on the TrueNAS side with no success, including basically 777 for the user & group.  

I'm not clear why making group changes as @the0remora suggested would make a difference, and one of those groups appears related to system time (I guess install is changing the date on the files?).  Also unclear to me why the install process needs to do a chown when RetroNAS is already running as the correct user.  I assumed chown would only be used in the "fix permissions" feature and would be setting the owner to the RetroNAS user.

Exact error below.  @danmons if I could vote for the next in a YouTube video series it would be setting up RetroNAS with the data directory backed by a proper NAS like TrueNAS.  Your level of explanation of *nix fundamentals would be very much appreciated as I'm trying to sort out permissions issues between the two systems (and don't spend a ton of time in Linux).  Personally I'm running RetroNAS on a Debian 11 VM on ProxMox if that makes a difference (I followed your setup video for VMs and expect it doesn't matter).

`failed: [localhost] (item=[{'src': 'nec/pcenginecd', 'mister': 'TGFX16-CD', 'retropie': '', 'batocera': '', 'recalbox': '', 'retroarch': '', 'ops2l': '', 'ps3netsrv': '', 'fspd': ''}, {'name': 'saves', 'enabled': 'yes', 'systems': 'yes'}]) => {"ansible_loop_var": "item", "changed": false, "gid": 1000, "group": "homeuser", "item": [{"batocera": "", "fspd": "", "mister": "TGFX16-CD", "ops2l": "", "ps3netsrv": "", "recalbox": "", "retroarch": "", "retropie": "", "src": "nec/pcenginecd"}, {"enabled": "yes", "name": "saves", "systems": "yes"}], "mode": "0775", "msg": "chown failed: [Errno 1] Operation not permitted: b'/storage/retronas/saves/nec/pcenginecd'", "owner": "nobody", "path": "/storage/retronas/saves/nec/pcenginecd", "size": 2, "state": "directory", "uid": 65534}`

**Comment by sairuk** [comment]
noting we dont support truenas nor have a setup to test against, the chown is required because the running user of the playbook should be root while the permissions on the folders is expected to be those of your unprivd user

what does you nfs export opts look like? root_squash for example wont allow chown since root is not root in that case

**Comment by jamescadd** [comment]
Good to know you don't support TrueNAS (I basically assumed it from seeing the network mount in Cockpit).  I'm not sure if I'm getting the settings that you want but here's an attempt.  If its easier to pull these from a terminal let me know how.

NFS Share settings
<img width="720" alt="Screen Shot 2022-03-19 at 11 00 09 AM" src="https://user-images.githubusercontent.com/2729218/159133033-f50dfb0e-cdc3-4399-a956-a054f34e71c1.png">

Dataset Permissions (not I'm not using ACL Manager.  RetroNAS runs as homeuser with the same id of 1000)
<img width="752" alt="Screen Shot 2022-03-19 at 11 02 53 AM" src="https://user-images.githubusercontent.com/2729218/159133075-42db4460-1e7d-4321-8cb3-7ce4aae82e38.png">

User settings
<img width="841" alt="Screen Shot 2022-03-19 at 11 04 24 AM" src="https://user-images.githubusercontent.com/2729218/159133136-38892b3c-a795-4023-a35d-1cfa45546969.png">

**Comment by sairuk** [comment]
this is going to be best effort/community supported from the TrueNAS/Synology side

Take a look at your export on the cli `/etc/exports` or in `/etc/exports.d/` looking at the screenshot i'd assume `root_squash` is used by the `maproot user` option being present but I don't know, you'd need to follow up with the TrueNAS project on how to work around it, if it is default

**Comment by the0remora** [comment]
> I'm not clear why making group changes as @the0remora suggested would make a difference, and one of those groups appears related to system time (I guess install is changing the date on the files?). Also unclear to me why the install process needs to do a chown when RetroNAS is already running as the correct user. I assumed chown would only be used in the "fix permissions" feature and would be setting the owner to the RetroNAS user.


I wanted to address the adding your user to groups. What you are seeing is a difference in Linux distributions and how they handle groupIDs. For instance I prefer the EndeavourOS flavor of Arch and it does not have GID 100 or 101, so I always make then and call them SynologyUser and SynologyAdmin. RetroNAS is debian based and so uses GID 100 for users and 101 does not exist.


If I run the ID command while logged in to my Synology I get "uid=1026($USERNAME) gid=100(users) groups=100(users),101(administrators)"

On my RetroNAS install I get "uid=1000($USERNAME) gid=1000($USERNAME) groups=1000($USERNAME),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),105(input),107(render),109(netdev),117(lpadmin),997(gpio),998(i2c),999(spi)" *Note I have not setup NFS on this install so I haven't changed my UID.

Finally on my EndeavourOS install I get this "uid=1026($USERNAME) gid=1026($USERNAME) groups=1026($USERNAME),3(sys),100(synologyusers),101(synologyadmin),982(rfkill),984(users),998(wheel),1000(autologin)

**Comment by jamescadd** [comment]
Thank you, I was able to get it to work by setting the following in the Advanced section of NFS Settings UI:
<img width="571" alt="Screen Shot 2022-03-19 at 12 18 57 PM" src="https://user-images.githubusercontent.com/2729218/159135416-0ea91218-8659-45cb-b84e-f45f566726d3.png">


Which ended up setting /etc/exports to this:
`/mnt/tank/retronas -alldirs -maproot="root":"wheel"`

I had already added groups 100 and 101 to the user as was suggested earlier, I am not sure if these matter on TrueNAS or not.  Appreciate all the help!
