### ISSUE TITLE
All Symlinks except for MiSTer are broken

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#128]
As the title suggests, I have checked the retrosmb\retronas\roms share and all of the system folders do not show any roms at all (e.g. PS1, PS2, PS3, Mega CD etc).

![image](https://user-images.githubusercontent.com/97349996/156072717-b7fa5276-7e98-4e53-8160-8d5640118d5d.png)

![image](https://user-images.githubusercontent.com/97349996/156072754-ea6f94b2-050e-4892-bf7a-b38dfd6a736d.png)

Only MiSTer is showing the ROMS that I have on retronas so the Symlinks appear to be completely broken.

![image](https://user-images.githubusercontent.com/97349996/156072808-0a1ca372-a566-49ef-9e6f-1ce7f32adf97.png)

![image](https://user-images.githubusercontent.com/97349996/156072856-3847f407-f973-4bcc-8a41-d93efcea6237.png)

How can I reset this so they are all restored?

**Comment by sairuk** [comment]
hrrm OK, you may have an old link structure?

Log into the shell (Terminal through Cockpit interface if you have it installed) and type this and give us the output please

Exchange `/data/retronas` for whatever your global top level directory is

`ls -la /data/retronas/mister`

and

`ls -la /data/retronas/mister/games`

**Comment by davedoc1984** [comment]
Ok this isn't looking good, what on earth has happened? :(

![image](https://user-images.githubusercontent.com/97349996/156075384-2a82ac1d-4bec-46f0-b8e4-5cde20e2792d.png)

**Comment by sairuk** [comment]
please confirm your retronas_path is `/data/retronas` before we worry too much

`grep retronas_path /opt/retronas/ansible/retronas_vars.yml`

**Comment by davedoc1984** [comment]
Yes it is

![image](https://user-images.githubusercontent.com/97349996/156076277-fec9a05d-79de-4828-a9c1-824a1722c4da.png)

**Comment by sairuk** [comment]
hrrrm, please cat out the mister share smb conf

`grep path /etc/samba/retronas_mister.conf`

**Comment by davedoc1984** [comment]
![image](https://user-images.githubusercontent.com/97349996/156076688-ee939aa0-0a0f-4a75-a4f4-92a9356ffdcf.png)

I have lost all PS2 and PS3 content I had yet my Storage Stats on Cockpit still shows that Data has been used up.

**Comment by davedoc1984** [comment]
Ok I have found my content is still there on /storage so the files are still intact but the symlinks are broken and not picking this content up :(

![image](https://user-images.githubusercontent.com/97349996/156076959-76ac9e9d-b99a-4178-a243-864333498322.png)

**Comment by sairuk** [comment]
Your data is not lost, so we are fine there.

You have not set your global path correctly, you can see here that the samba configuration is reading from `/storage` whereas retronas is reading from `/data/retronas` so this will affect the ability of retronas to correctly create the symlinks in the correct location

As such you are seeing odd results in the commands

You will need to correct your gobal path as per this video I believe https://www.youtube.com/watch?v=IyY80z5Vl_U&t=802s

please confirm your link structure in /storage is correct for mister

`ls -la /data/retronas/mister`
`ls -la /data/retronas/games`

**Comment by sairuk** [comment]
At some point your data path has been changed which is functionally breaking for retronas

**Comment by davedoc1984** [comment]
Understood. Changing it back to /storage now and reinstalling Services as per the video.

**Comment by sairuk** [comment]
You may also need to check you're existing samba configurations as I have demonstrated about to make sure pathing is correct

We need a better way to handle changes and reinstalls, we want to track installations so we can provide uninstallation paths for services and configuration updates as part of this we should look into how we can detect and update global path changes on a reinstall. 

Not sure what that solution looks like at this stage but we should be thinking about it.

**Comment by davedoc1984** [comment]
Actions taken

Changed Top Level back to /storage

Reinstalled all Services (MiSTer, PS2 and PS3). All working fine. Closing issue
