### ISSUE TITLE
FSP Load GC An error has occurred

### ISSUE THREAD

**Issue by s3anami** [danmons/retronas#130]
Using GCLoader to boot latest Swiss 1250
Using SD2SP2 with 8 GB SD card (tried 2 GB as well) for configuration device settings (attempting to use GCLoader writeback gives no SD card error)
Attempting to load game using FSP from RetroNAS
It starts patching the necessary DOL files to boot the game
Goes into game and gives an error has occurred turn the power off
Games load just loading from GCLoader

**Comment by sairuk** [comment]
I see you are working with the upstream project here https://github.com/emukidid/swiss-gc/issues/651

This does not appear to anything to do with the RetroNAS deployment at this stage, so we will give the upstream project a chance to debug your issue

**Comment by s3anami** [comment]
one of the switches in the mix was not functioning properly, sorry for wasting your time

**Comment by sairuk** [comment]
Thanks for letting us know
