### ISSUE TITLE
gogrepo not downloading games files.

### ISSUE THREAD

**Issue by the0remora** [danmons/retronas#132]
When I run the Full or Download/update all tasks from the menu they only download the bonus content. However Download/update Single does work properly. I attempted to look through the gogrepo retronas scripts after looking at the readme on the gogrepo github but I don't know enough about bash scripting to fix the problem, and nothing jumped out at me.

Tested by:
1) Deleting all downloaded files => running Download/update all
2) Deleting all files and gog-manifest.dat => running FULL
3) Deleting specific game => running Download/update single game => Selected deleted game.

**Comment by sairuk** [comment]
Interesting, there was another problem with gogrepo recently where it started reporting xml errors during manifest generation in issue https://github.com/danmons/retronas/issues/117

perhaps the on disk manifest incomplete?

**Comment by sairuk** [comment]
Can confirm this behaviour, i just tried a full resync/download and it is only leeching extras

**Comment by the0remora** [comment]
> Interesting, there was another problem with gogrepo recently where it started reporting xml errors during manifest generation in issue #117
> 
> perhaps the on disk manifest incomplete?

I can confirm that I am seeing the xml error whenever I run the script and with all options.

**Comment by sairuk** [comment]
Looking at the code, that xml problem is breaking looking up the md5 sum of the installer and subsequently it is not available during downloading.

If you apply the fix as reported here https://github.com/eddie3/gogrepo/issues/63 and do an update i believe it should correct the behaviour.

i am running an update now but it is going to take a while before I can confirm, but I can definitely see a change in the debug data now showing the download output for each game coming during the update. I expect this will then be available for in the loaded manifest data during download

**Comment by sairuk** [comment]
Yeh ok so thats solved that for most games, there are a couple that still report xml errors which I need to look at specifically (Control is one) but i've patched the gogrepo.py and pointed our install at my fork instead of the main project

https://github.com/sairuk/gogrepo

**Comment by sairuk** [comment]
OK, i've applied the fix from @TheLateNightFlight, added gzipped content support (the aforementioned Control issue) and moved our installer to my fork. I am going to close this one off.
