### ISSUE TITLE
Update - RomDir does not generate famicom_disk folder

### ISSUE THREAD

**Issue by bluemistP** [danmons/retronas#133]
Maybe a little thing, when I run tools - ROM Import I encounter this error:

```
Failed to file output directory /mnt/dietpi_userdata/retronas/roms/nintendo/famicom_disk
```

So I used Update - RomDir function but I don't see famicom_disk in the output. Could you please check?

**Comment by sairuk** [comment]
You are correct that path was not being created, I have pushed a fix for that now, you'll just need to rerun the Update -RomDir again

**Comment by bluemistP** [comment]
Confirmed, thank you!
