### ISSUE TITLE
Feature request: DreamPI

### ISSUE THREAD

**Issue by davewongillies** [danmons/retronas#136]
Since you seem to be putting just about everything else in, adding [DreamPI](https://github.com/Kazade/dreampi) to RetroNAS would be cool too 🥳 

Its bit of a moonshot since it involves connecting up the modem to a PI along with the other bits and pieces: http://blog.kazade.co.uk/p/dreampi.html

**Comment by sairuk** [comment]
Hi thanks for the suggestion, we have this over on our [Ideas](https://github.com/danmons/retronas/wiki/Ideas) page for potential future integration
