### ISSUE TITLE
Update - RomDir does not generate X folder

### ISSUE THREAD

**Issue by bluemistP** [danmons/retronas#137]
If you remember I raised this issue:
https://github.com/danmons/retronas/issues/133

I realized that there are a lot more folders that are not being generated in the Update - RomDir function, plus there are inconsistencies with the folder structure compared to the older versions of RetroNAS which initially did not have Update - RomDir.

For example the old RetroNAS had its Famicom Disk folder in _\nintendo\famicom\disk_ , while new one is in _\nintendo\famicom_disk_

I would suggest that you do a clean sweep/check of the functionality, but if you want a sample of how many folders are missed, please check this Nintendo one:
![image](https://user-images.githubusercontent.com/98199107/157233295-489addd4-1493-419a-b078-57b4d1de1c7e.png)

**Comment by sairuk** [comment]
Thanks, we're still migrating stuff across and some other stuff has moved around since the initial deploys. There is a lot of work still to do in this space

**Comment by sairuk** [comment]
I've pushed some updates and corrected that famicom disk folder, thanks for the report.

**Comment by bluemistP** [comment]
> Thanks, we're still migrating stuff across and some other stuff has moved around since the initial deploys. There is a lot of work still to do in this space

No problem, this is understood.
I see a couple of references towards other-emulator folder structures (retropie, batocera, recalbox, retroarch) so I am looking forward to check how you people will attack this challenge (I have almost all those systems in different boxes)

**Comment by sairuk** [comment]
I've done a review of old v new based on the data in an old commit and believe i've captured everything now, so i will close this off.

RE: other structures, the intent is to get data on their folder structures and symlink to location on RetroNAS (i.e symlink into a directory batocera at the top level of the share)
