### ISSUE TITLE
FSP directory layout creation errors

### ISSUE THREAD

**Issue by Coaleb2** [danmons/retronas#139]
When trying to install fsp for gamecube it gives me the error in the screensho
![Screenshot from 2022-03-10 14-05-37](https://user-images.githubusercontent.com/17729793/157745786-e9371ad8-5697-41a0-a15b-02a9b8bff145.png)
t

**Comment by sairuk** [comment]
thanks for letting us know, have identified an error in one of our imported playbooks, this has now been corrected. please run RetroNAS again so it updates itself and reinstall fsp.
