### ISSUE TITLE
ps3netsrv install error

### ISSUE THREAD

**Issue by gnuisance** [danmons/retronas#14]
Having no success with ps3netserv installation on my pi4/4gb w/ retropie image

It fails at this part:
TASK [ps3netsrv - build layout] **********************************************************************************************************************************************
failed: [localhost] (item={'src': '../../roms/sony/playstation3/games', 'dest': 'GAMES'}) => {"changed": false, "gid": 1000, "group": "pi", "item": {"dest": "GAMES", "src": "../../roms/sony/playstation3/games"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /data/retronas/ps3/ps3netsrv/GAMES/../../roms/sony/playstation3/games", "owner": "pi", "path": "/data/retronas/ps3/ps3netsrv/GAMES", "size": 4096, "src": "../../roms/sony/playstation3/games", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/sony/playstation3/iso', 'dest': 'PS3ISO'}) => {"changed": false, "gid": 1000, "group": "pi", "item": {"dest": "PS3ISO", "src": "../../roms/sony/playstation3/iso"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /data/retronas/ps3/ps3netsrv/PS3ISO/../../roms/sony/playstation3/iso", "owner": "pi", "path": "/data/retronas/ps3/ps3netsrv/PS3ISO", "size": 4096, "src": "../../roms/sony/playstation3/iso", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/sony/playstation2/dvd', 'dest': 'PS2ISO'}) => {"changed": false, "gid": 1000, "group": "pi", "item": {"dest": "PS2ISO", "src": "../../roms/sony/playstation2/dvd"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /data/retronas/ps3/ps3netsrv/PS2ISO/../../roms/sony/playstation2/dvd", "owner": "pi", "path": "/data/retronas/ps3/ps3netsrv/PS2ISO", "size": 4096, "src": "../../roms/sony/playstation2/dvd", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/sony/playstation1/iso', 'dest': 'PSXISO'}) => {"changed": false, "gid": 1000, "group": "pi", "item": {"dest": "PSXISO", "src": "../../roms/sony/playstation1/iso"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /data/retronas/ps3/ps3netsrv/PSXISO/../../roms/sony/playstation1/iso", "owner": "pi", "path": "/data/retronas/ps3/ps3netsrv/PSXISO", "size": 4096, "src": "../../roms/sony/playstation1/iso", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/sony/playstationportable/iso', 'dest': 'PSPISO'}) => {"changed": false, "gid": 1000, "group": "pi", "item": {"dest": "PSPISO", "src": "../../roms/sony/playstationportable/iso"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /data/retronas/ps3/ps3netsrv/PSPISO/../../roms/sony/playstationportable/iso", "owner": "pi", "path": "/data/retronas/ps3/ps3netsrv/PSPISO", "size": 4096, "src": "../../roms/sony/playstationportable/iso", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/videos/bdiso', 'dest': 'BDISO'}) => {"changed": false, "gid": 1000, "group": "pi", "item": {"dest": "BDISO", "src": "../../roms/videos/bdiso"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /data/retronas/ps3/ps3netsrv/BDISO/../../roms/videos/bdiso", "owner": "pi", "path": "/data/retronas/ps3/ps3netsrv/BDISO", "size": 4096, "src": "../../roms/videos/bdiso", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/videos/dvdiso', 'dest': 'DVDISO'}) => {"changed": false, "gid": 1000, "group": "pi", "item": {"dest": "DVDISO", "src": "../../roms/videos/dvdiso"}, "mode": "0775", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /data/retronas/ps3/ps3netsrv/DVDISO/../../roms/videos/dvdiso", "owner": "pi", "path": "/data/retronas/ps3/ps3netsrv/DVDISO", "size": 4096, "src": "../../roms/videos/dvdiso", "state": "directory", "uid": 1000}
	to retry, use: --limit @/opt/retronas/ansible/install_ps3netsrv.retry

PLAY RECAP *******************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1  

Doesn't seem to think the sources exist.
So far I've:
-run as root
-manually created the directories
-edited the playbook to use the full path /data/retronas/roms/
all to no avail. 

I've also checked out the install_ps3netsrv.retry file and it seems to be empty save for one line:
localhost
I've also tried updating permissions through the retronas script, with no success.

Any help would be appreciated! And if this is a dumb fix please forgive me :P

**Comment by ChaOConnor** [comment]
Same issue.  Error I'm getting references the build of the tool:
```

TASK [ps3netsrv - Install build tools] ********************************************************************************************************************************************************************************************************************************************************
[WARNING]: Updating cache and auto-installing missing dependency: python-apt
failed: [localhost] (item=['make', 'automake', 'autoconf', 'gcc', 'g++', 'meson', 'ninja-build', 'curl', 'wget', 'build-essential', 'unzip', 'libmbedtls-dev', 'libmbedtls12', 'coreutils']) => {"ansible_loop_var": "item", "changed": false, "cmd": "apt-get install --no-install-recommends python-apt -y -q", "item": ["make", "automake", "autoconf", "gcc", "g++", "meson", "ninja-build", "curl", "wget", "build-essential", "unzip", "libmbedtls-dev", "libmbedtls12", "coreutils"], "msg": "E: Package 'python-apt' has no installation candidate", "rc": 100, "stderr": "E: Package 'python-apt' has no installation candidate\n", "stderr_lines": ["E: Package 'python-apt' has no installation candidate"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage python-apt is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  python3-apt-dbg:armhf python3-apt:armhf python3-apt-dbg python3-apt\n  python-apt-doc python-apt-common\n\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Package python-apt is not available, but is referred to by another package.", "This may mean that the package is missing, has been obsoleted, or", "is only available from another source", "However the following packages replace it:", "  python3-apt-dbg:armhf python3-apt:armhf python3-apt-dbg python3-apt", "  python-apt-doc python-apt-common", ""]}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

**Comment by davedoc1984** [comment]
I have the same issue with PS3netsrv.

**Comment by danmons** [comment]
Many thanks for the report.  This has been fixed with a new commit this morning.  Please re-test and let me know how you go.

**Comment by ChaOConnor** [comment]
> Many thanks for the report. This has been fixed with a new commit this morning. Please re-test and let me know how you go.

Just tried it, works great, errors gone.  Thank you!!!

**Comment by danmons** [comment]
Great. Closing it up, but please report back if it breaks for anyone.

**Comment by eb0687** [comment]
I am getting this error when trying to install ps3netserv:

Currently running debian and the folder onto which i have asked retronas to point at is an SMB share mounted in my ~/ directory

I have setup the 3DS tool this way and it works fine, its just ps3netserv that keeps erroring out...

`TASK [ps3netsrv - build layout] **************************************************************************************************************************************************************
failed: [localhost] (item={'src': '../../roms/sony/playstation3/games', 'dest': 'GAMES'}) => {"ansible_loop_var": "item", "changed": false, "gid": 1000, "group": "samus", "item": {"dest": "GAMES", "src": "../../roms/sony/playstation3/games"}, "mode": "0755", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /home/samus/truenas-storage/ps3/ps3netsrv/GAMES/../../roms/sony/playstation3/games", "owner": "samus", "path": "/home/samus/truenas-storage/ps3/ps3netsrv/GAMES", "size": 0, "src": "../../roms/sony/playstation3/games", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/sony/playstation3/iso', 'dest': 'PS3ISO'}) => {"ansible_loop_var": "item", "changed": false, "gid": 1000, "group": "samus", "item": {"dest": "PS3ISO", "src": "../../roms/sony/playstation3/iso"}, "mode": "0755", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /home/samus/truenas-storage/ps3/ps3netsrv/PS3ISO/../../roms/sony/playstation3/iso", "owner": "samus", "path": "/home/samus/truenas-storage/ps3/ps3netsrv/PS3ISO", "size": 0, "src": "../../roms/sony/playstation3/iso", "state": "directory", "uid": 1000}
failed: [localhost] (item={'src': '../../roms/sony/playstation2/dvd', 'dest': 'PS2ISO'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "PS2ISO", "src": "../../roms/sony/playstation2/dvd"}, "msg": "Error while linking: [Errno 95] Operation not supported: b'../../roms/sony/playstation2/dvd' -> b'/home/samus/truenas-storage/ps3/ps3netsrv/PS2ISO'", "path": "/home/samus/truenas-storage/ps3/ps3netsrv/PS2ISO"}
failed: [localhost] (item={'src': '../../roms/sony/playstation1/iso', 'dest': 'PSXISO'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "PSXISO", "src": "../../roms/sony/playstation1/iso"}, "msg": "Error while linking: [Errno 95] Operation not supported: b'../../roms/sony/playstation1/iso' -> b'/home/samus/truenas-storage/ps3/ps3netsrv/PSXISO'", "path": "/home/samus/truenas-storage/ps3/ps3netsrv/PSXISO"}
failed: [localhost] (item={'src': '../../roms/sony/playstationportable/iso', 'dest': 'PSPISO'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "PSPISO", "src": "../../roms/sony/playstationportable/iso"}, "msg": "Error while linking: [Errno 95] Operation not supported: b'../../roms/sony/playstationportable/iso' -> b'/home/samus/truenas-storage/ps3/ps3netsrv/PSPISO'", "path": "/home/samus/truenas-storage/ps3/ps3netsrv/PSPISO"}
failed: [localhost] (item={'src': '../../roms/videos/bdiso', 'dest': 'BDISO'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "BDISO", "src": "../../roms/videos/bdiso"}, "msg": "Error while linking: [Errno 95] Operation not supported: b'../../roms/videos/bdiso' -> b'/home/samus/truenas-storage/ps3/ps3netsrv/BDISO'", "path": "/home/samus/truenas-storage/ps3/ps3netsrv/BDISO"}
failed: [localhost] (item={'src': '../../roms/videos/dvdiso', 'dest': 'DVDISO'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "DVDISO", "src": "../../roms/videos/dvdiso"}, "msg": "Error while linking: [Errno 95] Operation not supported: b'../../roms/videos/dvdiso' -> b'/home/samus/truenas-storage/ps3/ps3netsrv/DVDISO'", "path": "/home/samus/truenas-storage/ps3/ps3netsrv/DVDISO"}

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0`
