### ISSUE TITLE
New install seems to be missing some folders

### ISSUE THREAD

**Issue by sairuk** [danmons/retronas#147]
### Discussed in https://github.com/danmons/retronas/discussions/146

<div type='discussions-op-text'>

<sup>Originally posted by **fantomdew** March 20, 2022</sup>
Greetings. i am not sure where to post this as far as a discussion vs an issue so i thought i would start here. I am doing a new install of RetroNas. Everything seems to go fine until i get to install the Mister section. I get errors and they seem to be pointing to missing folders. When i go into roms under Nintendo i noticed that the nes and snes folders are missing. There might be more but those are the two i see right off the bat. This seems to be similar to issues 133 and 137. I see they have been closed so i am not sure if i am doing something wrong or if perhaps something is missing on a fresh install?

thanks</div>

**Comment by sairuk** [comment]
Please get a screenshot of the error

**Comment by fantomdew** [comment]
![Errors](https://user-images.githubusercontent.com/101946302/159136138-b690200b-42c5-465d-beb3-3345fdfe94b9.PNG)
![Mister folders](https://user-images.githubusercontent.com/101946302/159136147-6b708ff9-7695-42ac-95f7-6a67b7a251ab.PNG)
![Mister Game Folders](https://user-images.githubusercontent.com/101946302/159136151-10b51f91-1fa6-45d9-a178-7e59340bfb9a.PNG)
![Nintendo folders](https://user-images.githubusercontent.com/101946302/159136156-67b46a05-9d8e-4621-87bc-4c929f340628.PNG)
![Root RetroNas](https://user-images.githubusercontent.com/101946302/159136157-3c6933f7-a065-4e5f-91b1-83ffd37e9fe0.PNG)


I screen capped the first set of errors. I also included a couple folder structures that were made during the install. 
Let me know what else i can provide for troubleshooting.
thanks

**Comment by sairuk** [comment]
What kind of filesystem are you using for the your RetroNAS storage? It appears your filesystem does not support symlinking

**Comment by fantomdew** [comment]
I am using fstab to mount a cifs/smb share from a Windows server. The file system on the Windows server is using NTFS.

**Comment by sairuk** [comment]
ok, mounting in a Windows based cifs share is outside of the scope of the core RetroNAS product so anything thereafter will be best effort/community support. We are happy to document/link to proven solutions form the community

You'll need to work out posix symlink compatibility on the Windows server side for this to be a compatible configuration for RetroNAS unfortunately.

We use symlinks for system level support and in our base generic rom paths setup so you will need to find out if Windows will support this and/or find an alternative solution if not.

**Comment by fantomdew** [comment]
Ok, thanks for the help. I will look into it and see what i might come up with.

**Comment by sairuk** [comment]
Thanks i'll close this issue and we can continue with your findings over on the original discussion
