### ISSUE TITLE
Mister Mount Issue

### ISSUE THREAD

**Issue by s3anami** [danmons/retronas#152]
Attempting to mount the retronas share to the mister after editing the cifs_mount.sh (not sure why the wiki says ini)
Double checked the settings and they seem fine.
Are their certain items that cannot exist on the mister local sd card for this to work possibly?

Get the following error output:
mount: /tmp/cifs_mount: cannot mount //192.168.1.200/mister read-only.
//192.168.1.200/mister not mounted

**Comment by sairuk** [comment]
If you create an ini file with the same name as the script, the script will read its settings from the ini. Using an ini file stops people from editing a script that may be overwritten at some point in the future and their settings lost.

If memory serves this can be representative of an auth problem, set your RetroNAS passwords through global configuration after installing Samba for MiSTer and try again.

If this doesn't work, as to why the cifs_mount.sh script is not working on MiSTer please review that with the script owners https://github.com/MiSTer-devel/Scripts_MiSTer,

**Comment by thehughhefner** [comment]
@s3anami As the wiki says, you need create an ini file called cifs_mount.ini and in this ini file, type in the following information:

SERVER="ipaddress"  
SHARE="mister"
USERNAME="pi"
PASSWORD="yourpipassword"
WAIT_FOR_SERVER="true"
MOUNT_AT_BOOT="true"

So in your Scripts folder on the mister sd card, you should have:
cifs_mount.ini
cifs_mount.sh
cifs_umount.sh

Do not edit the cifs_mount.sh

**Comment by s3anami** [comment]
doesn't make a difference

**Comment by s3anami** [comment]
i used dmesg to get more info its not liking the login. Are there certain complexity restrictions on the password?
] CIFS: Attempting to mount \\192.168.1.200\mister
[  530.239278] CIFS: Status code returned 0xc000006d STATUS_LOGON_FAILURE
[  530.239337] CIFS: VFS: \\192.168.1.200 Send error in SessSetup = -13
[  530.245809] CIFS: VFS: cifs_mount failed w/return code = -13

**Comment by sairuk** [comment]
Not from the RetroNAS side, no, you should use global configuration to ensure your samba password is set (after installing samba) then enter those details into the dcifs_mount ini.

The other option may be whatever complexity you have in your password is something the MiSTer scripts can't handle properlu

**Comment by s3anami** [comment]
it breaks on complex passwords with special characters so that's the reason

**Comment by sairuk** [comment]
no just update the password, samba needs to be installed before trying to set the password thats all

**Comment by s3anami** [comment]
closing this but i think it should be noted that passwords need to be simple non special chars or their is potential of breaking mister compat
