### ISSUE TITLE
MiSTer: Remove iso folder from PSX directory

### ISSUE THREAD

**Issue by thehughhefner** [danmons/retronas#153]
Hi,
Since iso is not supported on the psx core, this folder can be deleted

**Comment by Paradox** [comment]
iso is a general term for bin/cue or iso, or any other cd image format you use, but, I do agree that if we want an iso or bin or, even chd directory, we should add it ourselves, and, not have it hardcoded, like this, not just PSX, but, any rom folder that uses cd images.

**Comment by Paradox** [comment]
This also would go for any other type of subfolder, and should be removed, all together, not just from the Mister folder structure.

**Comment by sairuk** [comment]
the folder is required by ps3netsrv service currently and as such appears in the playstation directory that MiSTer links to in our generic folder structure, this will need to remain

Additional discussion on directory structure in relation to MiSTer can be continued [here](https://github.com/danmons/retronas/discussions/60)
