### ISSUE TITLE
Ansible doesn't properly ensure /usr/lib/systemd/system exists as a directory when installing FSP on Debian 11

### ISSUE THREAD

**Issue by minorOffense** [danmons/retronas#157]
I installed retronas on Debian 11 (which I realize isn't raspbian) but the folder where the FSP service is trying to be saved is `/usr/lib/systemd/system` and doesn't exist in debian 11. The directory `/usr/lib/systemd/user` does exist if you want to use that instead. But if you want to standardize on `/usr/lib/systemd/system` then there should be an ansible task to ensure that directory exists before trying to use it.

I haven't written a ton of ansible but I do know Puppet pretty well. So ensuring that a resource exists before using it is pretty key in ensuring cross-distro compatibility.

If you add something like the following to the install_fsp.yml before copying the service unit into place.

```
- name: Create systemd unit folder
  ansible.builtin.file:
    path: /usr/lib/systemd/system
    state: directory
    mode: '0755'
```

So you could use the ansible facts to detect the OS and change the system unit folder location to one that's already available or just ensure that folder is present regardless of the distro before writing files to it.

I didn't update the ansible on my local install but creating that folder does in fact allow FSP to install properly.

I'll open a PR referencing this issue for review.

**Comment by sairuk** [comment]
yeh we need to start using `/etc/systemd/system/` instead of these dirs because as you've noted they aren't available everywhere by default. I put some notes on your pull request so please refer to those for now
