### ISSUE TITLE
Add ability to pass through configuration options via env variables for Docker support

### ISSUE THREAD

**Issue by natewalck** [danmons/retronas#164]
Hey all! 

I'm loving this project and started looking at what might be needed to get it working in docker. I figure this would be a good place to start the discussion.

Basically, every interactive question should be able to be overwritten using an environment variable that is present at the time that the script is run. 

For instance in `retronas_vars.yml.default` it contains:
```
retronas_path: "/data/retronas"
retronas_user: "pi"
retronas_root: "/opt/retronas"
retronas_etherdfs_interface: "eth0"
```
So we would need an env var of  `RETRONAS_USER` which could be passed in and if present, it doesn't prompt asking which user to use.

`retronas_path` and `retronas_root` can remain default as we can use a docker volume to mount something in to that path.

Once you get to the main install menu, being able to trigger each menu item via env var or using a docker volume pass a yaml file in (or both!) would be ideal.

In the meantime, I can work on a basic Dockerfile and builds that require manual configuration. In theory, once it is configured, it should be fine to start, but I need to dig into that some more.

**Comment by sairuk** [comment]
Thanks for the input, we have an open discussion for docker already [here](https://github.com/danmons/retronas/discussions/2) so please move your discussion there

all work around Docker will be moving to branches in the retronas-dist repo because an aio approach is not going to be good enough for everyone

**Comment by natewalck** [comment]
Thanks! TIL about discussions (I checked all open issues)
