### ISSUE TITLE
Add docker repo for RetroNas

### ISSUE THREAD

**Issue by natewalck** [danmons/retronas#165]
It would be helpful to keep the main app apart from the Docker configs, so perhaps it would be useful to have a repo just for this work.

Something like `retronas-docker` would follow the general convention.

Thanks!

**Comment by natewalck** [comment]
Here is an example of what this repo would look like to start: https://github.com/natewalck/retronas-docker 

This is literally 20-30 minutes worth of work, so it is extremely sparse until we figure out a method for passing variables in.

**Comment by sairuk** [comment]
The intent was to include docker in retronas-dist so please work on this there.

https://github.com/danmons/retronas-dist/tree/docker-aio
