### ISSUE TITLE
"...check back in about a month..."

### ISSUE THREAD

**Issue by SpiralBrad** [danmons/retronas#169]
"By all means use it, but if you're not an intermediate to advanced user, check back in about a month when the major framework has settled down and it's ready for beta status, and more user friendly."

This was added to the README on January 14 in commit 376aec5.

It is now April 12, nearly three months later.

**Comment by SpiralBrad** [comment]
Confused why this was closed without comment.

Is this not an 'issue'?  Because I would think so; it is something that needs addressed.

**Comment by sairuk** [comment]
yeh i dunno what i did here, sorry.

we'll fix up the readme

**Comment by audiocrush** [comment]
@SpiralBrad 
I'm not sure but that comment seems to carry a lot of bad vibes
This is people developing a cool project in their spare time.. if they don't feel like working on it or they might have someting else more important in their lives going on, it just happens to be that way

**Comment by SpiralBrad** [comment]
@audiocrush Stop caring about vibes.  It needs addressed, it's not something I can address myself, so I made an issue.

**Comment by danmons** [comment]
We're all about the good vibes here.  Wording has been change to reflect the "rolling release" nature of the project.
