### ISSUE TITLE
Awk error 

### ISSUE THREAD

**Issue by IvanCaregnato** [danmons/retronas#175]
Fresh start, just install rom importer and cockpit. Everytime I ssh it (terminal or cockpit's terminal) it gives me few lines with this message:

awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator

Raspberry pi4, updated, awk 5.0.1

**Comment by sairuk** [comment]
What distro is this installed on? 

debian bullseye comes with mawk 1.3.4.20200120 by default.
whereas the buntu's default to gawk 5.0.1, 

debian bullseye is our target platform but we can look into what we can do to make it more portable, if you can confirm distro

**Comment by IvanCaregnato** [comment]
Debian bullseye, I've just updated apt-get update and full-upgrade

**Comment by sairuk** [comment]
interesting thanks, I've pushed a fix i could test against (g)awk 5.0.1 so next RetroNAS run it should update, but pulling the latest code. 

Please let me know how you go.

**Comment by IvanCaregnato** [comment]
is there anything I could test?

**Comment by sairuk** [comment]
great thanks, going to close this off
