### ISSUE TITLE
Top Level Directory not shown correctly on main menu

### ISSUE THREAD

**Issue by IvanCaregnato** [danmons/retronas#176]
In main menu it always displays pi/pi, no matter what, but in the configuration menu it displays it correctly.
I've tried to reinstall few times, same issue. Default, BTW, is opt/data if I remember well.
Rpi4, bullseye updated, fresh installation. I've only changed TLD to /storage as I use it an USB Disk as main storage.

<img width="532" alt="Schermata 2022-04-24 alle 10 31 07" src="https://user-images.githubusercontent.com/39193450/164967768-22a1999b-0807-4a7f-9bfe-0720e14e1869.png">

<img width="538" alt="Schermata 2022-04-24 alle 10 31 25" src="https://user-images.githubusercontent.com/39193450/164967774-aad8c264-4e3b-450a-ae55-d39b234575f8.png">

**Comment by sairuk** [comment]
huh, good pickup thanks, I'll take a look
