### ISSUE TITLE
PS4 fpkg (*.pkg) support for HB-Store

### ISSUE THREAD

**Issue by Gkiokan** [danmons/retronas#177]
Hi mate,

I just got a feedback that my [HB-Store CDN Server](https://github.com/Gkiokan/hb-store-cdn-server) tool would be great if it could supports RetroNAS as base path.  
I will test the RetroNAS once I have time for it to figure out how to implement it though.  
  
Currently there are a few endpoints and stuff to be made to get the pkgs working on the hb-store app on the ps4 side.  
So therefore my Tool would only act as a proxy here and prepare the necessary data structure and provide the needen stuff.
  
As my tool just deep scans the given base path for all *.pkg files, I assume that it would be enough if users just put in the NAS address as base path and let it do it's job.  Which seems to be working fine by the user.  But apperently it scans all the NAS folders I guess which adds a bit delay.

**Comment by sairuk** [comment]
Converting to discussion

Please let us know when this tool is ready to be added
