### ISSUE TITLE
ps3netserv failed to start on install

### ISSUE THREAD

**Issue by jnackmclain** [danmons/retronas#183]
I am running on Debian 11 on an x64 system. I tried setting up ps3netserv via the install script however the smb share is not created and cockpit says "Failed to start" for ps3netsrv.
The folders were created and symlinks properly setup, however the service is not working.
I have mister, xbox 360, ps2, and standard smb shares working properly.

This is the result of checking the service in the retronas ui

systemctl --no-pager --full status ps3netsrv

● ps3netsrv.service - ps3netsrv for PlayStation3 with CFW/HEN and webMAN-MOD
     Loaded: loaded (/lib/systemd/system/ps3netsrv.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-05-05 22:10:19 CDT; 5min ago
    Process: 148928 ExecStart=/opt/retronas/bin/ps3netsrv /mnt/data-ext4/ps3/ps3netsrv (code=exited, status=203/EXEC)
   Main PID: 148928 (code=exited, status=203/EXEC)
        CPU: 2ms

May 05 22:10:19 retronas systemd[1]: ps3netsrv.service: Scheduled restart job, restart counter is at 10.
May 05 22:10:19 retronas systemd[1]: Stopped ps3netsrv for PlayStation3 with CFW/HEN and webMAN-MOD.
May 05 22:10:19 retronas systemd[1]: ps3netsrv.service: Start request repeated too quickly.
May 05 22:10:19 retronas systemd[1]: ps3netsrv.service: Failed with result 'exit-code'.
May 05 22:10:19 retronas systemd[1]: Failed to start ps3netsrv for PlayStation3 with CFW/HEN and webMAN-MOD.

**Comment by eukatech** [comment]
I have the same problem and i seen problems in the log :

TASK [ps3netsrv - Install from source code] ****************************************************************************
task path: /opt/retronas/ansible/install_ps3netsrv.yml:76
changed: [localhost] => {"changed": true, "cmd": "/opt/retronas/scripts/install_ps3netsrv.sh 2>&1 | tee /opt/retronas/log/install_ps3netsrv.log", "delta": "0:00:01.422024", "end": "2022-05-06 20:38:38.647170", "rc": 0, "start": "2022-05-06 20:38:37.225146", "stderr": "", "stderr_lines": [], "stdout": "Configuring build directories...\nDownloading ps3netsrv source code...\n\n\n--2022-05-06 20:38:37--  https://github.com/\nResolving github.com (github.com)... 140.82.121.4\nConnecting to github.com (github.com)|140.82.121.4|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: unspecified [text/html]\nSaving to: 'index.html'\n\n     0K .......... .......... .......... .......... .......... 1.18M\n    50K .......... .......... .......... .......... .......... 2.38M\n   100K .......... .......... .......... .......... .......... 7.21M\n   150K .......... .......... .......... .......... .......... 3.71M\n   200K ....                                                   8.04T=0.08s\n\n2022-05-06 20:38:37 (2.43 MB/s) - 'index.html' saved [209221]\n\nunzip:  cannot find or open ps3netsrv*.zip, ps3netsrv*.zip.zip or ps3netsrv*.zip.ZIP.\n\nNo zipfiles found.\n/opt/retronas/scripts/install_ps3netsrv.sh: line 22: cd: ps3netsrv*/ps3netsrv: No such file or directory\n\nERROR: Neither directory contains a build file meson.build.\nninja: Entering directory `buildrelease'\nninja: error: loading 'build.ninja': No such file or directory\nMoving binary to RetroNAS bin dir...\nmv: cannot stat 'buildrelease/ps3netsrv': No such file or directory\nCleaning up...\nAll done!", "stdout_lines": ["Configuring build directories...", "Downloading ps3netsrv source code...", "", "", "--2022-05-06 20:38:37--  https://github.com/", "Resolving github.com (github.com)... 140.82.121.4", "Connecting to github.com (github.com)|140.82.121.4|:443... connected.", "HTTP request sent, awaiting response... 200 OK", "Length: unspecified [text/html]", "Saving to: 'index.html'", "", "     0K .......... .......... .......... .......... .......... 1.18M", "    50K .......... .......... .......... .......... .......... 2.38M", "   100K .......... .......... .......... .......... .......... 7.21M", "   150K .......... .......... .......... .......... .......... 3.71M", "   200K ....                                                   8.04T=0.08s", "", "2022-05-06 20:38:37 (2.43 MB/s) - 'index.html' saved [209221]", "", "unzip:  cannot find or open ps3netsrv*.zip, ps3netsrv*.zip.zip or ps3netsrv*.zip.ZIP.", "", "No zipfiles found.", "/opt/retronas/scripts/install_ps3netsrv.sh: line 22: cd: ps3netsrv*/ps3netsrv: No such file or directory", "", "ERROR: Neither directory contains a build file meson.build.", "ninja: Entering directory `buildrelease'", "ninja: error: loading 'build.ninja': No such file or directory", "Moving binary to RetroNAS bin dir...", "mv: cannot stat 'buildrelease/ps3netsrv': No such file or directory", "Cleaning up...", "All done!"]}

**Comment by sairuk** [comment]
looks like the download is failing on newer versions, thanks for the repo.

**Comment by sairuk** [comment]
should be fixed with a reinstall, the downloads were failing due to some change on the github side. 

Please give it a go and let me know.

**Comment by jnackmclain** [comment]
Just checked and confirming this is  resolved. Thank you very much!
