### ISSUE TITLE
Colecovision rom import

### ISSUE THREAD

**Issue by crazyp** [danmons/retronas#196]
when running rom import it seems to be trying to import them into a non existent directory instead of the directory that was created at data/retronas/roms/coleco/colecovision.  the error I receive is 
"Failed to file output directory /data/retronas/roms/other/coleco_colecovision"

**Comment by sairuk** [comment]
ah ok, thanks yeh hardcoded paths is scripts are bad

I have pushed a fix to main for that now, thanks for letting us know
