### ISSUE TITLE
GOGRepo not working with new installs

### ISSUE THREAD

**Issue by CLangeland** [danmons/retronas#218]
Hi,

When setting up the gogrepo-addon, I cannot login

attempting gog login as 'email' ...
cannot continue, gog is asking for a reCAPTCHA :(  try again in a few minutes.
exiting...

Googling the error, gives me some hints on creating the gog-cookies.dat manually, but no real info on how to do that. Should perhaps be outlined in the doc? 

The Chrome-addon "Cookies.txt" was supposedly an easy way to get the needed info, but just pasting that info into the /home/pi/.gogrepo/gog-cookies.dat was not the solutiuon.

**Comment by sairuk** [comment]
yeh also see the same but this is not a RetroNAS issue to fix. gogrepo application needs to understand/fix why it is being captcha'd

**Comment by unabletoconnect2429** [comment]
potential fix https://github.com/eddie3/gogrepo/issues/65#issuecomment-1250761919

is it possible to implement in the fork that retronas uses?

**Comment by sairuk** [comment]
workaround added to fork, closing this for now
