### ISSUE TITLE
SD Card Corrupted. Reinstalled Retronas how to add Existing Drive back in?

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#22]
My SD Card became corrupted so it would no longer boot to Retronas. I have re-installed it but I do not want to lose the original Hard Drive I had setup.

How do I "Add" that Hard Drive back in so Retronas will use it WITHOUT it creating a new Drive and erasing the contents?

**Comment by danmons** [comment]
Run the RetroNAS installer, then install Cockpit. You can then use Cockpit to mount the drive without the partitioning/formatting steps (you should see the partition and file system still on the disk). 

Once mounted, set the mount path in RetroNAS and rerun your service installers. These will just install and configure the services. No data will be overwritten.

**Comment by davedoc1984** [comment]
Perfect thanks dan. The issue I had in the end was because of the USB to SATA Adapter which I have seen before. It reports back that the drive has no partitions on it :) I need to throw that Adapter away as its caught me out once before.

Changed the USB Adapter for another one and now I can see the original EXT4 partition and could mount it as /storage again and everything is happy (MiSTer CIFS, PS2SMB etc).

**Comment by sairuk** [comment]
I think this should feed some basic troubleshooting/recovery doco in the wiki before it is closed, there is a possibility that more people my run into this situation
