### ISSUE TITLE
I can't see my disk (Raspberry Pi OS Lite 64-bit)

### ISSUE THREAD

**Issue by widgetfonda** [danmons/retronas#24]
Hi,

I can't see my disk from the cockpit and I can't format/partition it.

There was this error in the logs: Error loading modules: Error opening directory “/usr/lib/aarch64-linux-gnu/udisks2/modules”: No such file or directory

I was able to remove this error by creating the directory /usr/lib/aarch64-linux-gnu/udisks2/modules, but after a reboot I still don't see my disk.

The error no longer appears in the logs.

Is the problem caused by my 64-bit Raspberry Pi OS installation?

**Comment by davedoc1984** [comment]
I use the 32bit Lite install for my Pi 4B and all is working fine.

**Comment by widgetfonda** [comment]
I reinstalled Raspberry Pi OS 32-bit, I have almost the same error in the logs : Error loading modules : Error opening directory "/usr/lib/arm-linux-gnueabihf/udisks2/modules" : No such file or directory

I still don't see my disk.

Is it necessary to format it in a special way before plugging it on the raspberry ?

For information, the hard disk is a WD My Book 8Tb in USB3, and I have a raspberry pi 4.

**Comment by widgetfonda** [comment]
I just tested with another external hard drive and this time I can see my drive despite the error message in the logs.

I suppose that the WESTERN DIGITAL My Book 8 TB (WDBBGB0080HBK) is not compatible with RetroNAS. It works perfectly under Windows 10.

Someone with this model can confirm?

**Comment by danmons** [comment]
I don't have one of these "My Book" devices to test, although I have heard that they use custom tools to encrypt them. It should still show up as a raw device though.

If you're ok with command line use, are you able to plug the device in, run the following, and share the output? (Just copy/paste the text output via ssh if possible). 

`sudo fdisk -l`

That will just ask Linux to list every attached disk and partition it can recognise, whether it's formatted/mounted or not.

**Comment by widgetfonda** [comment]
You can close the issue, it works now.

I plugged it back into my Windows PC, did a clean command with diskpart, plugged it back into my raspberry and it works. I don't know what happened.

In the logs I still have Error loading modules: Error opening directory "/usr/lib/arm-linux-gnueabihf/udisks2/modules" : No such file or directory which is displayed as long as I don't create the directory by hand. But it doesn't seem to cause a problem.

For the 64-bit OS version, the message is : Error loading modules: Error opening directory “/usr/lib/aarch64-linux-gnu/udisks2/modules”: No such file or directory

**Comment by danmons** [comment]
Glad it's working.  

The udisks error appears to be a dependency check of Cockpit, although from what I see on the Cockpit github issues it's just an annoying message and not an error.  I can add something into the Cockpit installer all the same to create empty directories and make that message go away.
