### ISSUE TITLE
Failed to start FSP File Service Protocol

### ISSUE THREAD

**Issue by tanuki2k** [danmons/retronas#241]
FSP fails to start form a cold boot. However after the system is up and running it can manually be started and works fine. 

8:56 PM
Started FSP File Service Protocol.
systemd
8:54 PM
Failed to start FSP File Service Protocol.
systemd
8:54 PM
fspd.service: Failed with result 'exit-code'.
systemd
8:54 PM
fspd.service: Start request repeated too quickly.

**Comment by sairuk** [comment]
what platform are you running this on? fsp on my rpi4 is fine from cold boot

**Comment by tanuki2k** [comment]
Debian via a VM on my Snology NAS.  This came up in terminal:
```
-- Journal begins at Fri 2022-06-24 18:38:28 AEST, ends at Tue 2022-08-30 18:41:00 AEST. --
Jun 24 20:14:06 retronas fspd[10189]: DIRLISTCACHE 100 entries (0 used). Memory: 120 hdr, keys 800 static + 0 dynamic, entries 2400 static + 0 dynamic. Hit rat>
Jun 24 20:14:06 retronas fspd[10189]: DIRSTATCACHE 30 entries (0 used). Memory: 120 hdr, keys 240 static + 0 dynamic, entries 1920 static + 0 dynamic. Hit rati>
Jun 24 20:14:06 retronas fspd[10189]: FPCACHE 20 entries (0 used). Memory: 120 hdr, keys 160 static + 0 dynamic, entries 480 static + 0 dynamic. Hit ratio: 0 h>
Jun 24 20:35:39 retronas fspd[10232]: DIRLISTCACHE 100 entries (0 used). Memory: 120 hdr, keys 800 static + 0 dynamic, entries 2400 static + 0 dynamic. Hit rat>
Jun 24 20:35:39 retronas fspd[10232]: DIRSTATCACHE 30 entries (0 used). Memory: 120 hdr, keys 240 static + 0 dynamic, entries 1920 static + 0 dynamic. Hit rati>
Jun 24 20:35:39 retronas fspd[10232]: FPCACHE 20 entries (0 used). Memory: 120 hdr, keys 160 static + 0 dynamic, entries 480 static + 0 dynamic. Hit ratio: 0 h>
-- Boot b8a8d3feb200454fa344432b7b3b06b1 --
Jun 24 20:36:12 retronas fspd[615]: /data/retronas/gamecube/swiss: No such file or directory
Jun 24 20:36:12 retronas fspd[633]: /data/retronas/gamecube/swiss: No such file or directory
Jun 24 20:36:12 retronas fspd[637]: /data/retronas/gamecube/swiss: No such file or directory
Jun 24 20:36:12 retronas fspd[640]: /data/retronas/gamecube/swiss: No such file or directory
Jun 24 20:36:12 retronas fspd[649]: /data/retronas/gamecube/swiss: No such file or directory
Jun 24 21:38:34 retronas fspd[1094]: DIRLISTCACHE 100 entries (0 used). Memory: 120 hdr, keys 800 static + 0 dynamic, entries 2400 static + 0 dynamic. Hit rati>
Jun 24 21:38:34 retronas fspd[1094]: DIRSTATCACHE 30 entries (0 used). Memory: 120 hdr, keys 240 static + 0 dynamic, entries 1920 static + 0 dynamic. Hit ratio>
Jun 24 21:38:34 retronas fspd[1094]: FPCACHE 20 entries (0 used). Memory: 120 hdr, keys 160 static + 0 dynamic, entries 480 static + 0 dynamic. Hit ratio: 0 hi>
-- Boot 507a9c4d12fb49048aaae8cc3bf84e46 --
```
The really odd thing is the folder is there.

**Comment by sairuk** [comment]
Safe to assume `/data/retronas` or the swiss folder is a mount? I am assuming the mount hasn't come up in time.

Our default service file only has a condition for `network-online.target`  you may need to add an override for the service file to only start after your folders are mounted in.

**Comment by tanuki2k** [comment]
/data/retronas is a mount so yes that would make senses *face palm*

**Comment by sairuk** [comment]
can you let me know when we're good to close this issue off, some notes on how you worked around with an override it would be appreciated. Might help someone else out later

`systemctl edit fsp.service` will create an override in `/etc/systemd/system` and you will be able to add some conditions e.g. `ConditionPathExists` for your mount pointing at the `swiss` dir. 

I may just add that to the main project but i need to check how it works. I think using `Requires=` changes the behaviour.

**Comment by tanuki2k** [comment]
Thanks for the support, all good to close. I'll give the suggestions a go but even if I'm unsuccessful (I know enough to be dangerous) manually restarting the service isn't the end of the world.

**Comment by sairuk** [comment]
Alright thanks for the feedback
