### ISSUE TITLE
Cannot mount mister

### ISSUE THREAD

**Issue by drpaneas** [danmons/retronas#248]
Hi, this is a clean fresh install from my RPi 4B
and I am getting this message:

```
$ ./cifs_mount.sh
mount: /tmp/cifs_mount: cannot mount //192.168.178.62/mister read-only
//192.168.178.62/mister not mounted
```

The permissions for the retroras directory seem fine:

```bash
$ ls -ld raid0/
drwxrwxr-x 10 pi pi 4096 Sep 23 21:57 raid0/
```

```bash
$ ls -lah
total 52K
drwxrwxr-x 10 pi   pi   4.0K Sep 23 21:57 .
drwxr-xr-x  3 root root 4.0K Sep 23 21:20 ..
drwxrwxr-x 69 pi   pi   4.0K Sep 23 21:56 bios
drwxrwxr-x  2 pi   pi   4.0K Sep 23 22:07 config
drwxrwxr-x  2 pi   pi    16K Sep 23 21:19 lost+found
drwxrwxr-x  7 pi   pi   4.0K Sep 23 21:59 mister
drwxrwxr-x 69 pi   pi   4.0K Sep 23 21:50 roms
drwxrwxr-x 69 pi   pi   4.0K Sep 23 21:56 saves
drwxrwxr-x 69 pi   pi   4.0K Sep 23 21:56 savestates
drwxrwxr-x  2 pi   pi   4.0K Sep 23 21:56 wallpapers
```

FYI: I've fixed the permissions via the ansible target you have in the global settings (it was mainly root), e.g. `changed ownership of '/mnt/raid0/mister/games/TeleStrat' from root:root to pi:pi`.

Looking at the Samba logs:

```bash
Sep 23 22:42:06 raspberrypi smbd[65860]: pam_unix(samba:session): session closed for user nobody
Sep 23 22:42:06 raspberrypi smbd[65861]: pam_unix(samba:session): session closed for user nobody
```

**Comment by drpaneas** [comment]
Solution:

Go _again_ to the global settings and set _again_ the username, the password and the group.
Now go back to and re-install the Samba service.

From the logs, it works fine now:

```
./cifs_mount.sh
Waiting for 192.168.178.62
//192.168.178.62/mister mounted
BIOS mounted
games mounted
saves mounted
savestates mounted
wallpapers mounted
Done!
```

and samba server log:

```
Sep 23 22:49:04 raspberrypi smbd[72363]: pam_unix(samba:session): session opened for user pi(uid=1000) by (uid=0)
Sep 23 22:49:46 raspberrypi smbd[73707]: pam_unix(samba:session): session opened for user pi(uid=1000) by (uid=0)
```

Since I didn't changed neither of the settings (username, group, password) I would expect this ti work in the first time.

**Comment by sairuk** [comment]
the authentication details need to be configured for samba after installation to permit login, samba uses a different auth program than the system mech. It Windows stuff, people still use windows so we have to put up with it. 

To set this it is done through the configuration option you mentioned. auth is different to perms and needs to be set.

Thanks for sharing the solution for others, nature of the beast
