### ISSUE TITLE
PSP folder link

### ISSUE THREAD

**Issue by eukatech** [danmons/retronas#249]
for emuelec, the psp folder does not link correctly (emuelec->psp) (roms-sony-playstationportable)

**Comment by sairuk** [comment]
we link it to the iso subfolder at the moment which it is linking correctly, iso/ciso was the most likely use case at the time.

Can you elaborate on why this needs to change? we will probably need to change batocera and recalbox as well.

**Comment by eukatech** [comment]
the rest of the directory's on recalbox/batocera/emulec work fine from what ive seen.. they dont use an iso directory inside. like playstation and saturn are fine.. just not psp

**Comment by sairuk** [comment]
i've run the emuelec installer today and it installs fine linked to the iso directory as we have directed it so i'm not sure what is supposed to be wrong here.

i have pushed a commit to the testing branch that brings emuelec psp inline with batocera and recalbox, thanks for the report
