### ISSUE TITLE
[Talk] Switch ansible from playbook to roles

### ISSUE THREAD

**Issue by willoucom** [danmons/retronas#25]
I am in love with this project, and i'm also in love with Ansible.

At the current stage of the project, I think that having most of the logic in playbooks will lead to future problems, such as disaster recovery or update difficultie

I also think the current system with shell scripts and dialog is an excellent solution that offers great possibilities and should be future-proof.

I have a lot of experience with Ansible, so it's possible that these changes seem simple to me while it may not be so clear to you, and I apologize for that. Please note that I am offering my help in making these changes, I am also willing to make them if you are comfortable with the demonstration. 

About the changes I want to propose.

At first, create a single playbook and move current logic in different roles. 
The syntax is roughly the same between playbook and roles.
In this playbook, we add tags on each entry, one for each role. 
Then, update the shell scripts to call tag instead of different playbook.yml (doc: https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html)

For example, if we move `install_cockpit.yml` inside a role with the tag "cockpit" in the main `playbook.yml`, we can call this role with the command : `ansible-playbook -t cockpit playbook.yml` and this is where the magic start to shine, we can call multiple tags in one command, `ansible-playbook -t cockpit,samba playbook.yml`

Next step of the magic, we can also use host variables to further simplify the operation (doc: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#adding-variables-to-inventory).

For example, we set in the playbook the "cockpit" role is attached to the variable "cockpit", then in the inventory, we add the variable "cockpit" to the host localhost. 
The variable file is a plain ini file or a yaml file, and since the file will be saved on disk, the user's configuration will persist. 
Then we only have to run `ansible-playbook playbook.yml` to apply the exact same configuration each time, permitting the user to update his installation with a simple and unique command. 

The conversion from playbook to role can be done one playbook at a time and with minor modifications each time. 
There is many other things we can do with Ansible, but I suggest to keep it simple. 

Thank you so much for your time, I look forward to discussing this topic with each of you.

**Comment by sairuk** [comment]
With the understanding that this project is in an early alpha state and arguably may be for some time, as i have looked through the structure i have had similar thoughts. That being said I think this goes beyond just ansible, the maintainability, contribution info, etc needs to be revisited to ensure the project can mature without becoming unruly.

In regards to the roles, I would suggest you fork the project and create a branch with a proposal for switching some basic functionality to a role so we can see a working example, bonus points for handling some alternate targets. 

I would be interested in seeing the approach you take with this as I was going to look into the same but am focusing elsewhere atm.

**Comment by sairuk** [comment]
I think this technical discussion would be better suited to discussions, not issues so we can formulate a way forward and keep this architectural discussions separate from issues. If possible can we consider moving this to a thread in discussions?

https://github.com/danmons/retronas/discussions

**Comment by willoucom** [comment]
The discussion is created here: https://github.com/danmons/retronas/discussions/43
