### ISSUE TITLE
everything on a NAS, multi-MiSTer resource sharing?

### ISSUE THREAD

**Issue by drpaneas** [danmons/retronas#251]
The update_all.sh script offers a variety of options, such as organize the _Arcade folder and sort it appropriately. If you enable this option, the way the script is handling this is via _symlinks_.

```bash
ln -s '/media/fat/_Arcade/gameA' '/media/fat/_Arcade/_Organized/_1\ 0-9/gameA'
```

This is failing, because you cannot have symlink on samba. I've tried some configurations I've found to StackOverflow but the outcome is that this is nasty and it's not going to work properly, so just don't do it. There are 3 solutions to my knowledge for this issue:

1. Do not mount the `_Archade` and similar `_*` folders, but use them via your SDCard.
2. Mount the folders BUT make sure you are not using any features of the `update_all.sh` that is going to create symlinks. Stuff like better organization or better names have a high probability of creating symlinks and this is not going to work.
3. Umount. Run the script to download the new arcade games and create the new symlinks. scp the folders into the RetroNAS. Mount again the RetroNAS samba share.

**Comment by drpaneas** [comment]
Probably updating the wiki with relevant information, seems to be the action item for this.

**Comment by sairuk** [comment]
while this isn't a RetroNAS issue an example of the error output for reference, this issue should be raised with the projects so they can check the destination before attempting use it in this way or document the incompatibility between features. 
```
Organizing 2357 MRAs.

MRA                                          Core       Year Manufactu. Category
################################################################################
1941- Counter Attack (JP).mra                jtcps1     1990 Capcom     Shooter 
Traceback (most recent call last):
  File "/tmp/_arcade-organizer.sh", line 1185, in <module>
    run()
  File "/tmp/_arcade-organizer.sh", line 1181, in run
    ao.organize_all_mras()
  File "/tmp/_arcade-organizer.sh", line 1143, in organize_all_mras
    self.organize_single_mra(mra)
  File "/tmp/_arcade-organizer.sh", line 817, in organize_single_mra
    self.create_alphabetic()
  File "/tmp/_arcade-organizer.sh", line 898, in create_alphabetic
    self.create_symlink(self._config['ORGDIR_09'])
  File "/tmp/_arcade-organizer.sh", line 861, in create_symlink
    self._infra.make_symlink(self._mra_path, self._basename_mra, directory)
  File "/tmp/_arcade-organizer.sh", line 360, in make_symlink
    os.symlink(src, dst)
OSError: [Errno 95] Operation not supported: '/media/fat/_Arcade/_alternatives/1941  Counter Attack -Japan-.mra' -> '/media/fat/_Arcade/_Organized/_1 0-9/1941- Counter Attack (JP).mra'
FINISHED: _ARCADE-ORGANIZER
```

However users can work around this by editing cifs_mount.ini and add the following

```
ADDITIONAL_MOUNT_OPTIONS="mfsymlinks"
```

I've updated the wiki page to reflect this info, thanks
