### ISSUE TITLE
PS3netsrv issue

### ISSUE THREAD

**Issue by Jman1290** [danmons/retronas#253]
Ps3netsrv isnt running. Ive tried file permissions, reinstalling ect always get the same issue. Weird thing is all the other things ive tried work fine (FTP, ps2, SMB ect). When I check it i get the following

systemctl --no-pager --full status ps3netsrv● ps3netsrv.service - ps3netsrv for PlayStation3 with CFW/HEN and webMAN-MOD Loaded: loaded (/lib/systemd/system/ps3netsrv.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Tue 2022-10-04 22:24:26 EDT; 2min 27s ago Main PID: 143626 (code=exited, status=203/EXEC) CPU: 3msOct 04 22:24:26 pi systemd[1]: ps3netsrv.service: Scheduled restart job, restart counter is at 12.Oct 04 22:24:26 pi systemd[1]: Stopped ps3netsrv for PlayStation3 with CFW/HEN and webMAN-MOD.Oct 04 22:24:26 pi systemd[1]: ps3netsrv.service: Start request repeated too quickly.Oct 04 22:24:26 pi systemd[1]: ps3netsrv.service: Failed with result 'exit-code'.Oct 04 22:24:26 pi systemd[1]: Failed to start ps3netsrv for PlayStation3 with CFW/HEN and webMAN-MOD.Press [Enter] to continue...

**Comment by sairuk** [comment]
something is definitely broken there. Can you give us some more detail about your OS version and hardware? thanks

**Comment by sairuk** [comment]
also let us know if you are on the `main` branch. you can check in the header of the main menu of retronas.

github seems to have changed something recently which broke some of our installers ps3netsrv may be failing because of it

**Comment by sairuk** [comment]
github seem to be lazy loading in the assets dropdown now so its not available to curl

i've commit a fix that uses the github api and some jq magic into the testing branch, if you want that fix you'll need to move to the testing branch or wait until i roll it up into main. that shouldn't be too long, i just need to test a couple of installers.

see: https://github.com/danmons/retronas/commit/7bd4f4987eb6abbb8e8c8973827a773523098fa8

thanks for the report

**Comment by Jman1290** [comment]
That fixed it! Thank you so much!
