### ISSUE TITLE
Fenrir Web Server

### ISSUE THREAD

**Issue by s3anami** [danmons/retronas#255]
Couple questions
The wiki references the service being available on 33194 after install, but the rest of the troubleshooting references 31994, is this a typo?

Also I appear to be having an error
 When running sudo /usr/local/bin/FenrirServer --dir /data/retronas/fenrir-ode-webserver --port 31994 --verbose

21:06:38 INFO  /tmp/webserver/src/server.c:41: Cache cd image folder
21:06:38 INFO  /tmp/webserver/src/server.c:45: start http server
2022-10-14 01:06:38 1 mongoose.c:3033:mg_open_li Failed to listen on http://0.0.0.0:31994, errno 98
2022-10-14 01:06:38 1 mongoose.c:3316:mg_listen  Failed: http://0.0.0.0:31994, errno 98
2022-10-14 01:06:38 2 mongoose.c:2490:mg_mgr_fre All connections closed

The application is accessible via the browser and shows nothing here and is able to be connected to over telnet over 31994

**Comment by sairuk** [comment]
> is this a typo?
yes thanks, fixed

> Also I appear to be having an error When running ....
the webserver runs as a systemd service, it'll be running in the background as the installed service (error 98 is address already in use). you'll need to stop the systemd service before trying to run it manually

there is also no need to run the webservice as root (sudo) you should run it as your normal retronas user

> The application is accessible via the browser and shows nothing here and is able to be connected to over telnet over 31994
this is correct behaviour, any other functional issues should be reported to the main project
