### ISSUE TITLE
Cannot change Top Level Directory to a mount point

### ISSUE THREAD

**Issue by Uplinkpro** [danmons/retronas#256]
Installed via Debian 11 with cockpit, Also using Cockpit-ZFS Manager.

Tried to create a storage pool in ZFS went to change top level directory to mountpoint EX: /pool/data/retronas the app tell me its not a valid choice. I have also tried a Raid 5 array via the inbuild cockpit raid system with no luck.

**Comment by sairuk** [comment]
did you point it at the block device(s) or the mount point? we check for a type `directory`  as part of changing the top level dir.

if you are absolutely sure you've got the correct location and we are not accommodating it somehow then run a `stat` on the location and paste the resulting output. 

You can edit the location manually in `/opt/retronas/ansible/retronas_vars.yml`  see `retronas_path`

**Comment by Uplinkpro** [comment]
stat pointed me in the right directory, it was a permissions issue on the mountpoint, setting chmod +rwx  and chaning group and user ownership on the point allowed for access
