### ISSUE TITLE
PS2 VMC - Memory cards taking MINUTES to save rather than seconds

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#26]
I think this can be considered as a bug. If you use the VMC (Virtual Memory Card) function within Open PS2 Loader with your Retronas PS2 share, it will take Minutes to save Memory Card game data rather than Seconds which most (including me initially) will lose patience and just turn off the PS2 assuming it has crashed when trying to save.

**Comment by sairuk** [comment]
Is this behaviour specific to the retroNas share or can it be reproduced on alternative samba/cifs shares with openps2loader?

**Comment by danmons** [comment]
Can you let me know the game title?  I'd previous played through "Silent Hill 2" completely with VMC over SMB1 and it was fine.

Also some specs - what type of PS2 (fat/slim), and what's your RetroNAS install on (RPi? VM? Wired? WiFi?). 

Also ensure you're testing the latest stable OpenPS2Loader from here:
https://github.com/ps2homebrew/Open-PS2-Loader/releases

There's the stable 1.1.0 which I'm using, but I see a 1.2.0 beta that's days old.  You can drop them on a USB thumbdrive and either run them direct (they'll read your existing OPL config from your first memory card), or you can use uLaunchELF to copy/paste it to your memory card.

**Comment by davedoc1984** [comment]
Ok my scenario is this. Ethernet for both the Pi4 with Retronas and my PS2's (yes I tried it with 2 different Slim Models SCPH-75003 and SCPH-90003.

Open PS2 Loader 1.10 Stabe.

Games used on both consoles Pro Evolution Soccer 2 and Pro Evolution Soccer 3 both with VMC's setup in Open PS2 Loader.

Both loading AND Saving the Option File that these games use takes minutes for some reason rather than 5 seconds on a Real Memory Card.

**Comment by danmons** [comment]
Thanks for updating. I'll start a discussion page soon on this. VMC support appears to be on a game by game basis, and is to do with OpenPS2Loader itself rather than any specific SMB implementation.

There are various online compatibility lists, however they seem to be quite out of date. Might be worth checking the open issues on the OpenPS2Loader GitHub too. 

I'm the meantime you can play the game over SMB and save to a real memory card. Likewise you can use uLaunchELF to back up memory card contents to a USB stick (or retrieve the files via FTP) if you're running low on MC space, or want to back up previous saves.

**Comment by davedoc1984** [comment]
Happy to work around it :) VMC worked ok with my Phat PS2 and OPL and VMC's so could always just fire that back up but love the idea of Network shared games on a NAS.

P.S. I am sure I read somewhere in the Net that other Linux based NAS Solutions had similar issues with VMC files. In fact here it is!!  https://github.com/ps2homebrew/Open-PS2-Loader/issues/327

**Comment by davedoc1984** [comment]
Ok so a little bit more to this. The Loading of Data from VMC's from the NAS is very FAST! Just the Saving of data that seems slow. Hopefully that helps in some way?

**Comment by danmons** [comment]
Interesting. I wonder if there's something going on with packet sizes or something related?

I might try to take a look with wireshark and see what's going on. 

There are HEAPS of Samba options to play with, so maybe we can do something server-side to help?

**Comment by danmons** [comment]
Potential fix here:
https://github.com/ps2homebrew/Open-PS2-Loader/issues/327

I can enable this just for the PS2 share (leaving the others alone). 

I'll do some testing on the games mentioned in this issue later in the week.

**Comment by danmons** [comment]
I've committed the two sync changes just now.  To test, re-run the "MiSTer FPGA CIFS config" to apply the change.

I won't have a chance to test this until later in the week, but throwing it out there for anyone else to test and report back if they have a moment.

**Comment by davedoc1984** [comment]
I will give this a go.

**Comment by davedoc1984** [comment]
Do you have to restart retronas after running the MiSTer FPGA CIFS Config? Its still slow to save to VMC's despite me running that again.

**Comment by davedoc1984** [comment]
Adding Strict Sync = No to /etc/samba/retronas_ps2.conf has made the saving much much faster :)

**Comment by danmons** [comment]
Apologies, I committed the changes to the MiSTer conf instead of the PS2 conf.  I've fixed that up and committed it now.  It's active for the general public.
