### ISSUE TITLE
PS3NETSRV PS3 Games Load Error

### ISSUE THREAD

**Issue by fredkht** [danmons/retronas#271]
Hi, my PS3netsrv was running smoothly for the past few months but just recently, I keep encountering Error message when i load the PS3 games from my RetroNAS.
I have tried reinstalling the PS3netsrv package from the retronas terminal, but still encounter the same issue.
Have also tried on my 3 CFW PS3 and encounter the same problem.
Webman Mod games scanning will work intermittently.
Is there any problem with PS3netsrv service lately?
Thanks,

**Comment by sairuk** [comment]
nothing on our side, have you check on the main project for any issue with the versions that you have installed?

https://github.com/aldostools/webMAN-MOD/issues

What is the actual error message? may help us debug stuff

you should be able to have a look at the service unit output and see if its throwing any error on the ps3netsrv side with `journalctl -u ps3netsrv`

Have a look at `dmesg` and see if there are any storage/net/io warnings on RetronNAS

Could there a network problem between your ps3s and retronas?

**Comment by fredkht** [comment]
I don't think there's a issue with my network as i was able to load my mister roms, Gamecube FSP from the RetroNas.
I have  a look at dmesg and there's no any storage/net/io warnings on RetroNas.

Please take a look on attached journalctl -u ps3netsrv photo.
![2022-11-30 (2)](https://user-images.githubusercontent.com/111871240/204783673-6f8de410-86e3-4023-a734-1ef9d4a40516.png)

**Comment by sairuk** [comment]
I would suggest you run the Permissions option from the Config menu on at the ps3netsrv folder and try again

see previous history of weird perm issues

- https://github.com/danmons/retronas/issues/48
- https://github.com/danmons/retronas/discussions/156

**Comment by fredkht** [comment]
I do "systemctl status ps3netsrv-perms.service" on the command line and this is the result that I get.

root@retronas:~# systemctl status ps3netsrv-perms.service
● ps3netsrv-perms.service - ps3netsrv for PlayStation3 permissions fix
     Loaded: loaded (/lib/systemd/system/ps3netsrv-perms.service; static)
     Active: inactive (dead) since Thu 2022-12-01 00:44:00 +08; 9s ago
TriggeredBy: ● ps3netsrv-perms.timer
    Process: 29488 ExecStart=/usr/bin/chown -RLc pi:pi /storage/ps3/ps3netsrv (code=exited, status=0/SUCCESS)
    Process: 29489 ExecStart=/usr/bin/chmod -Rc a-st,u+rwX,g+rwX,o+rX /storage/roms/videos/ (code=exited, status=0/SUCCESS)
    Process: 29490 ExecStart=/usr/bin/chmod -Rc a-st,u+rwX,g+rwX,o+rX /storage/roms/sony/ (code=exited, status=0/SUCCESS)
   Main PID: 29490 (code=exited, status=0/SUCCESS)
        CPU: 1.246s

Dec 01 00:43:59 retronas systemd[1]: Starting ps3netsrv for PlayStation3 permissions fix...
Dec 01 00:44:00 retronas systemd[1]: ps3netsrv-perms.service: Succeeded.
Dec 01 00:44:00 retronas systemd[1]: Finished ps3netsrv for PlayStation3 permissions fix.
Dec 01 00:44:00 retronas systemd[1]: ps3netsrv-perms.service: Consumed 1.246s CPU time.

**Comment by sairuk** [comment]
yeh all that looks normal from our end

**Comment by fredkht** [comment]
But how can I ensure whether my ps3netsrv permission fix has been enabled?

**Comment by fredkht** [comment]
This is the error I face when i try to load games from WebMan Mod.
![20221201_010950](https://user-images.githubusercontent.com/111871240/204864966-f2fe54c6-16d3-48ab-9d6d-e17f60183006.jpg)

**Comment by sairuk** [comment]
the output of the script you ran manually listed the ps3netsrv path with the intent being it was processed based on the nature of the script without error or the script would have failed.

also reading the output of `ps3netsrc-perms.service` mentioned the service ran `9s ago` as `Triggered By` the timer and each process returned `0/SUCCESS` meaning the `chown`/`chmod` commands where successfully run as listed. So our intended setup is running correctly.

```
Active: inactive (dead) since Thu 2022-12-01 00:44:00 +08; 9s ago
TriggeredBy: ● ps3netsrv-perms.timer
Process: 29488 ExecStart=/usr/bin/chown -RLc pi:pi /storage/ps3/ps3netsrv (code=exited, status=0/SUCCESS)
Process: 29489 ExecStart=/usr/bin/chmod -Rc a-st,u+rwX,g+rwX,o+rX /storage/roms/videos/ (code=exited, status=0/SUCCESS)
Process: 29490 ExecStart=/usr/bin/chmod -Rc a-st,u+rwX,g+rwX,o+rX /storage/roms/sony/ (code=exited, status=0/SUCCESS)
Main PID: 29490 (code=exited, status=0/SUCCESS)
```

This does not appear to be a RetroNAS ps3netsrv problem based on all the output.

I will try and find some time to test it directly on my PS3 when I can but that may take a while

**Comment by sairuk** [comment]
in the meantime you may want to open an issue here https://github.com/aldostools/webMAN-MOD/issues and they may be able to assist you debugging the ps3 side further incase its a corrupted webman issue

alternatively iirc webmanmod pulls the game data down to the internal storage to mount it (although that might only be for ps1/ps2 support, i can't remember offhand), confirm you have enough free space on the internal storage.

**Comment by fredkht** [comment]
Thanks.
I have a 1TB internal HDD in my PS3 and I have 0 games installed into it as I was using RetroNas to stream PS3 games all the time. I have about near to 900GB free space on my PS3.

**Comment by sairuk** [comment]
one final thought, just to confirm your correct RetroNAS user is `pi` as shown in the output of `ps3netsrv-perms` service?

**Comment by fredkht** [comment]
![2022-12-01 (2)](https://user-images.githubusercontent.com/111871240/204872664-15dc2f75-a1f3-4c84-a0df-96b4740772aa.png)

**Comment by sairuk** [comment]
just did a fresh install here and I can't see any issues with ps3netsrv on my end. Played a couple of games fine.

ps3netsrv is operating properly so i'll close this issue

We have a discussion for general use issues https://github.com/danmons/retronas/discussions/156
