### ISSUE TITLE
Xbox 360 Sharing

### ISSUE THREAD

**Issue by RetromanXGames** [danmons/retronas#293]
Through your youtube tutorials I managed to configure the PS2 and PS3 and both are working perfectly.
Here on the system, I installed the system on an ssd that I had stopped + HDD 12TB.
I even thought about formatting the HDD, but I didn't have another HDD with a similar size to play all the games that are organized here.
I managed to create symbolic links, anyway, both platforms work perfectly.
I couldn't make the Xbos 360 work, before I used it here on the Windows PC and it worked fine, I can even see the folder on the network by enabling SMB SHARING, before it was disabled because the folder where the 360 ​​games were on the PC windows appeared normally and I could put it as a source to load the games. I even looked on youtube for some information about retronas regarding the xbox 360, but I didn't find it.
I'll post my settings made on Xbox.
![20230113_130607 1](https://user-images.githubusercontent.com/74443668/212402635-3da3d285-7fab-4f45-b370-e0e62a81ab45.jpg)
![20230113_130552 1](https://user-images.githubusercontent.com/74443668/212402799-e4bc0706-fddb-408d-8236-cbf49a16593a.jpg)

I followed the youtube tutorial to configure Debian, pc name, username, etc..., I put exactly the same one used in the video.
I think I must be doing something wrong

**Comment by sairuk** [comment]
the sharename should be `xbox360` not `pi`

use the same computer name, username and password as the working ps2 setup

**Comment by RetromanXGames** [comment]
Thank you very much @sairuk! Now it worked perfectly, I still have a problem related to something else, do I open a new thread or can I post it here?

**Comment by sairuk** [comment]
new thread please or if its like this one where there is nothing broken on the RetroNAS side, please open a discussion after reading our doco if you still need help

https://github.com/danmons/retronas/discussions
