### ISSUE TITLE
Retronas no longer showing up in network

### ISSUE THREAD

**Issue by rogersta99** [danmons/retronas#296]
Retronas is no longer showing as connected in my network.  Checked for ip address by logging into my router and  pinging in terminal window.  Do I need to reinstall?  If so,  do I need to start from scratch with raspberry pi software?

**Comment by sairuk** [comment]
I'd suggest you plug your rpi into a display and see what it is doing on boot, also check cabling is secure (if any)

**Comment by rogersta99** [comment]
So it says I am in emergency mode.  I logged in ran through the system  logs.   It appears the last thing occurred on Jan 2.  

![image](https://user-images.githubusercontent.com/59268898/213034285-1345ec11-24ae-4d86-8abb-950ae18f0e99.jpeg)

**Comment by rogersta99** [comment]
![image](https://user-images.githubusercontent.com/59268898/213034353-523a76d8-2f33-43f2-aa6b-856f2b8a5819.jpeg)

![image](https://user-images.githubusercontent.com/59268898/213034382-cc1e7e87-2174-48a8-b743-4d125f48b06c.jpeg)

**Comment by sairuk** [comment]
thats a general rpios issue, nothing specific to retronas, perhaps you have run out of space on the root sd card?
