### ISSUE TITLE
Use netatalk 2.x release tarballs

### ISSUE THREAD

**Issue by rdmark** [danmons/retronas#300]
I noticed that you're using the bleeding edge of my netatalk 2.x fork in this script https://github.com/danmons/retronas/blob/main/ansible/templates/install_netatalk2x/install_netatalk2x.sh.j2

You may want to consider using a release tarball instead, e.g. https://github.com/rdmark/netatalk-2.x/releases/tag/netatalk-2-230301

I don't really have a development or testing process in my fork, so I may break things in HEAD at any time. The release tarballs have a modicum of quality assurance in place.

Now, I didn't confirm if this script is actually in use or not, so please ignore this if it's an abandoned script.

**Comment by sairuk** [comment]
Thanks, entirely a good idea. This was something i had intended to do actually and it didn't land on my updated to do list, probably just had one of those days.

Thanks for pointing it out, we do need to focus on releases where possible. I'll leave this open as a reminder to pull the latest archive from the github api data, we've changed some other installers to this lately (e.g. ps3netsrv).

**Comment by rdmark** [comment]
Optional, but you may also want to consider pivoting to upstream netatalk 2.2.8 https://github.com/Netatalk/netatalk/releases/tag/netatalk-2-2-8

I've spent the last year gradually bringing upstream up to speed with my 2.x fork. There are still some marginal advantages to 2.x, mostly around code quality and maintainability.

**Comment by danmons** [comment]
Thanks for the heads up.  I'll add a line or two in there to checkout the latest tag (which looks to line up with your release tarballs) so we're not always compiling main/HEAD. 

Great to hear you're pushing upstream back into line as well.  I'll take a look at that when I get some time.

**Comment by sairuk** [comment]
I've switched to pulling the latest netatalk-2-* tag while fixing #316
