### ISSUE TITLE
Can't seem to get Samba working with retronas user via Windows 11

### ISSUE THREAD

**Issue by Thraka** [danmons/retronas#307]
I can see the shares but when I try to enter them it asks for a user/pass and retronas/retronas doesn't work, nor does root/retronas.

Is there a config to just open it up with no user/pass and have full write access?

**Comment by sairuk** [comment]
setup the user and password in the Config menu after installing samba, we can't set the samba password until after installation of the samba libs

**Comment by Thraka** [comment]
I still get access denied trying to navigate to the directory.

I had checked the config menu but never saw an entry for "Samba" so I'm assuming you just mean the Password entry there. I set the password there to `retronas` and restarted the samba service. but it doesn't seem to change anything. 

For more information about my environment, I created a new samba share file `/etc/samba/dos.conf` for the dos-only drive that I created and mounted to /data/dosdrive:
![image](https://user-images.githubusercontent.com/2672110/229900163-a0ef9d32-234b-4753-92a8-186504951f5f.png)

In explorer I see the shares, but when I navigate to them, that's when retronas:retronas for user:pass just gives me access denied:

![image](https://user-images.githubusercontent.com/2672110/229900670-202a91c1-537e-40a0-8f83-f9b208e24940.png)

**Comment by sairuk** [comment]
Does the retronas share exhibit the same behaviour as your custom one?

Are the permissions correct on `/data/dosdrive`?

Also check `/var/log/samba/` for errors.

**Comment by Thraka** [comment]
Correct. I cannot get into the retronas share either. I'm not sure about permissions on `/data/dosdrive` how would I go about checking that?

-- examining logs now... --

**Comment by Thraka** [comment]
I do see these in the general log file:

![image](https://user-images.githubusercontent.com/2672110/229925874-243331a9-02ed-4ac3-838a-f53e170f9ba0.png)

**Comment by danmons** [comment]
> The retronas share also denies access. I'm not sure about permissions on `/data/dosdrive` how would I go about checking that?
> 

Re-run the password reset tool.  You can set the "new" password to the same as the "old" password if you like, that's fine.  But depending on what order you've installed things, Samba requires it's own separate password database (separate to the main Linux system), and if you haven't done that between installing Samba and setting up the shares, you often get those "access denied" messages.

You only need to do this once, directly after installing any Samba-based tool in RetroNAS.  A handful of other services require this step as well (a specific type of Apple File Sharing password database requires this too).  The RetroNAS password reset tool figures out what services you have installed, and sets that one password you enter for all installed services that can't use the internal Linux password system.

**Comment by Thraka** [comment]
Thanks for the reply's @danmons !

So in the previous response I had said that I did go to the `retronas` tool and try the `Config` section and then to `Password - Configure RetroNAS password` and set the password to `retronas` again. But that didn't seem to do anything.

Should I uninstall Samba via the retronas tool and then install it again then do password reset and see what happens?

**Comment by danmons** [comment]
Just for sanity's sake, make sure there's no cached credentials for RetroNAS. 

In Windosw 10/11, hold the Windows key and press R to bring up the run dialogue box.  In there, run:
```
shell:::{1206F5F1-0569-412C-8FEC-3204630DFB70}
```

This will bring up Windows Credentials Manager.  It holds stored passwords for various things.  If you tick "remember password" on anything in Windows itself (not in browsers/web stuff), they get stored here.

Click the "Windows Credentials" button in that box to see Windows specific stuff.  Dig through the list to see anything that looks like network sharing or specifically RetroNAS names/IPs.  If there are saved credentials there, delete them.  I've seen these mess up SMB shares before in Windows. 

> Should I uninstall Samba via the retronas tool and then install it again then do password reset and see what happens?

This certainly can't hurt.  It'll simply uninstall/reinstall the service, and leave your data behind.  The other thing is to ensure the on-disk permissions on your `/data/dosdrive` location inside Linux (not via SMB) are also set to the `retronas` user.  If this is some other user on-disk, the Samba service above it might have issues seeing what's on disk.

**Comment by Thraka** [comment]
Checking the list there aren't any cached credentials for that server. (I made sure not to "save this user for next time" when entering the user/pass 😁)

Here are the permissions via `ls -l`
![image](https://user-images.githubusercontent.com/2672110/229947713-e1f135da-048c-49b3-b295-755b4d2eead4.png)

I may have messed something up trying to get this working with the `777`

**Comment by Thraka** [comment]
I just ran `retronas` again and reinstalled the service. It didn't seem to make a difference, though I didn't notice a "uninstall" command, so I just ran Install again.

**Comment by danmons** [comment]
1) Can you also show the permissions on the `/data` directory at the top level? 

2) Do you have a second computer on the same network that you can test these shares from?  That will at least confirm if it's the server/RetroNAS side or the client/Windows side.

**Comment by danmons** [comment]
Oh, one other thing to test - I have seen at least one instance where a user couldn't browse SMB shares because their Windows firewall was disabled (i.e.: no firewalling was in place).  This is completely counter-intuitive, but it seemed that the only way they could get ANY SMB connections to work was by turning on the Windows Firewall and setting it to allow mode. 

Could you please double check your Windows firewall is in the "enabled" state.

**Comment by Thraka** [comment]
Yes, firewall is on and active. One thing I was curious about were the log errors I showed related to ntlm, considering the "install" from retronas configures those settings in the smb.conf file.

Good idea on getting some other computers talking to it to rule things out, I'll start testing. I have an old Win7 VM and a new Ubuntu VM I can test with. This is running on a VM in Unraid so I'll also see if the Unraid server itself can even talk to the share.

Here is the permissions on data:
![image](https://user-images.githubusercontent.com/2672110/230140901-6441fee5-f705-41f5-909b-9127e6078884.png)

**Comment by Thraka** [comment]
From the Ubuntu machine I was able to get right in, no problem. I want to guess that the server isn't invoking SMB2/3 and is instead trying to communicate with SMB1?

**Comment by Thraka** [comment]
Once you read this, feel free to close the issue. Thanks again for the troubleshooting help!

**Comment by sairuk** [comment]
we provide all versions of samba down to smb1

yes `retrosmb` is the share name samba is configured to use as per our doco https://github.com/danmons/retronas/wiki/Samba
