### ISSUE TITLE
Infinite Recursive Folders

### ISSUE THREAD

**Issue by s3anami** [danmons/retronas#308]
Had this happen a few times where it infinitely creates folders (in this case just iso folder over and over)
https://i.imgur.com/tezXHe4.png

**Comment by sairuk** [comment]
huh odd, thanks we will take a look. does it happen only after additional runs installing multiple items?

**Comment by sairuk** [comment]
thanks for reporting i've pushed a fix for now.

links would be created as entries if the link file already existed, to clean up the state people can run the following in `/data/retronas` (or equivalent) directory on the cli to clean up the bad links

`find -type l -exec rm {} \;`

**Comment by s3anami** [comment]
that removes all empty folders in the linux directory structure but doesn't seem to update what the share shows when i browse it in windows

**Comment by sairuk** [comment]
that command removes the `symlink` types under that directory which we use for mapping common systems with multiple names (e.g. `turbografx16cd` to `pcengine/iso`), and then they can be recreated correctly next run

windows may be doing caching? 

i don't have windows but can say browsing the shares in linux is ok now

**Comment by s3anami** [comment]
i was dumb and forgot my stuff was in /games not /data 
Oddly enough the entire folder structure was also created there in the directory you specified (data) for some reason.
I ran the command but its taking an awful long time to execute so not sure its working

**Comment by sairuk** [comment]
i'd assume it was created in `data` originally before it was changed to `games` as `data` is our default

the command has to check the type for every file, so the more files the longer it'll take.

closing this issue for now, the reported problem is fixed from our end 

thanks for the report
