### ISSUE TITLE
Netatalk 2: Fails to Install 

### ISSUE THREAD

**Issue by rmervine** [danmons/retronas#316]
I'm running a fresh install of RetroNAS that has Samba Installed. I attempted to install Netatalk 2. However, it fails at the end because it can't find the expected executables. Here is what I get at the end:
 

`failed:` [localhost] (item={'name': 'afpexpect.sh', 'dest': '/opt/retronas/bin/netatalk2x/bin', 'mode': '0754'}) => {"ansible_loop_var": "item", "changed": false, "checksum": "d47d2d132dac2089aa80590b3c5d8b783d45b753", "item": {"dest": "/opt/retronas/bin/netatalk2x/bin", "mode": "0754", "name": "afpexpect.sh"}, "msg": "Destination directory /opt/retronas/bin/netatalk2x/bin does not exist"} failed: [localhost] (item={'name': 'AppleVolumes.default', 'dest': '/opt/retronas/bin/netatalk2x/etc/netatalk'}) => {"ansible_loop_var": "item", "changed": false, "checksum": "fbfac377cf66e3ee448534f58b566fa3f991e467", "item": {"dest": "/opt/retronas/bin/netatalk2x/etc/netatalk", "name": "AppleVolumes.default"}, "msg": "Destination directory /opt/retronas/bin/netatalk2x/etc/netatalk does not exist"} failed: [localhost] (item={'name': 'afpd.conf', 'dest': '/opt/retronas/bin/netatalk2x/etc/netatalk'}) => {"ansible_loop_var": "item", "changed": false, "checksum": "4d82779143c9f91f4b066bdc97674f67fac5a500", "item": {"dest": "/opt/retronas/bin/netatalk2x/etc/netatalk", "name": "afpd.conf"}, "msg": "Destination directory /opt/retronas/bin/netatalk2x/etc/netatalk does not exist"} failed: [localhost] (item={'name': 'atalkd.conf', 'dest': '/opt/retronas/bin/netatalk2x/etc/netatalk'}) => {"ansible_loop_var": "item", "changed": false, "checksum": "b481a73018dc7b235afc030dcfd6775aad2fb766", "item": {"dest": "/opt/retronas/bin/netatalk2x/etc/netatalk", "name": "atalkd.conf"}, "msg": "Destination directory /opt/retronas/bin/netatalk2x/etc/netatalk does not exist"}``

I went to browse to /opt/retronas/bin. And I can see netatalk2x directory. However, nothing is in the directory.

**Comment by lockjock** [comment]
I am also experiencing this exact issue

**Comment by sairuk** [comment]
i've fixed this installation in 11eec22ee85b477829176143f1aa88faa709b7af the problem was down to a missing build dependency you'll need to be on the testing branch

**Comment by rmervine** [comment]
Confirmed fix. All successful by going to update and moving to testing branch. Also confirmed Netatalk is 2.0 is properly working from my Mac OS 9 VM.
