### ISSUE TITLE
XBOX Xlink repo decommissioned

### ISSUE THREAD

**Issue by mistertimely** [danmons/retronas#321]
E: The repository 'https://repo.teamxlink.co.uk/debian Release' does not have a Release file. W: Updating from such a repository can't be done securely, and is therefore disabled by default. W: See apt-secure(8) manpage for repository creation and user configuration details.

Unable to perform system updates due to broken repo.

**Comment by sairuk** [comment]
Thanks for the report 

Xlink is the broken tool,, XBOX manager is a different tool, i have updated the title to reflect this

repo.teamlink.co.uk has moved to dist.teamxlink.co.uk with instructions available at https://dist.teamxlink.co.uk/
