### ISSUE TITLE
NEOGEO CD folder on MISTer

### ISSUE THREAD

**Issue by IvanCaregnato** [danmons/retronas#323]
Recently has been moved to games/NeoGeo-CD, is there anything you could do to fix the shortcut?

**Comment by sairuk** [comment]
we haven't supported neogeocd in our symlinks until it was added to testing earlier today with the correct naming, rerun the mister installer to create the new symlink

**Comment by IvanCaregnato** [comment]
Hi sairuk, I've updated RetroNAS, rom's dir, extra and rerun MISTer CIFS installer but there is no NeoGeo-CD symlink that points to neogeocd folder on my storage... 

![Acquisizione schermata 18 07 2023 alle 20 14 06](https://github.com/danmons/retronas/assets/39193450/4a896920-fe4a-475c-bc95-b6e0f2520b5e)

**Comment by sairuk** [comment]
are you on the testing branch? 

Updates -> Branch then select testing from the menu

Alternatively if you don't want to run testing you can wait until we roll up the latest changes to the main branch

**Comment by IvanCaregnato** [comment]
mistery solved, thank you very much!

**Comment by IvanCaregnato** [comment]
hi saurik, do you know when this change will be included to main distribution? the new main mister with this new folder support is already live.
