### ISSUE TITLE
MiSTer: GAMEBOY/GAMEBOY2P and GBA/GBA2P should not share the same saves directory

### ISSUE THREAD

**Issue by tjanas** [danmons/retronas#333]
Save files for the GAMEBOY/GAMEBOY2P and GBA/GBA2P cores should not share the same directory:
```
pi@retronas:/storage/mister/saves$ ls -l GAMEBOY*
lrwxrwxrwx 1 root root 28 Jul 24 13:39 GAMEBOY -> ../../saves/nintendo/gameboy
lrwxrwxrwx 1 root root 28 Jul 24 13:39 GAMEBOY2P -> ../../saves/nintendo/gameboy
pi@retronas:/storage/mister/saves$ ls -l GBA*
lrwxrwxrwx 1 root root 35 Jul 24 13:39 GBA -> ../../saves/nintendo/gameboyadvance
lrwxrwxrwx 1 root root 35 Jul 24 13:39 GBA2P -> ../../saves/nintendo/gameboyadvance
```

For example, with the GAMEBOY core, `Tetris DX (World) (SGB Enhanced) (GB Compatible).sav` is 8K in size. With the GAMEBOY2P core, the same file would be 256K in size.

Per the [README](https://github.com/MiSTer-devel/Gameboy_MiSTer/tree/Gameboy2P) for GAMEBOY2P:

> Saves created contain savegames for both players.
> For compatibility, all saves are 256Kbyte in size, 128 KByte for each player.
> Saves can be copied from singleplayer, but only player 1 will have a savegame then.
> Saves can be copied to singleplayer, but when saved in singleplayer, the second player savegame is lost.

The same is true for GBA/[GBA2P](https://github.com/MiSTer-devel/GBA_MiSTer/tree/GBA2P).

Sharing the same save game directory can result in the save data being lost.

**Comment by sairuk** [comment]
interesting thanks, a unique situation. I expect we can add a unique save folder exceptions list somehow

**Comment by sairuk** [comment]
have added support for custom save/savestates dir for the 2p mister cores
