### ISSUE TITLE
MiSTer: symlinks created for saves that don't exist

### ISSUE THREAD

**Issue by tjanas** [danmons/retronas#335]
Many of the symlinks created in `/storage/mister/saves/` are unnecessary.
For example:

`AO486 -> ../../saves/other/intel_x86`
`mame -> ../../saves/mame/mame`

AO486 and the arcade cores (and several others) do not create or use save files.

**Comment by sairuk** [comment]
the saves dir linking we are doing is our standard based on a loop, we're not taking on the overhead of working out if a system from mister uses saves or not.
