### ISSUE TITLE
Blank list in bittorrent

### ISSUE THREAD

**Issue by 4gordi** [danmons/retronas#339]
Hi, everyone) I'm install retronas on clean raspbios x64 (rpi 3b+), install and config tools: ps2 samba, ps3netserver, batocera samba, cockpit, and bittorrent. All works fine, i have access to web deluge, but if i add (no metter how) torrent file, nothing happens, window of deluge with list is blank. If i copy torrents with samba to /bittorrent/auto-add, before some time in /bittorrent/downloading i see some files, but again nothing happens( In connection dialog window all config is fine, but i in lower right corner messege is "error, not enough space", but system is clear in 128Gb sd-card and external flash-drive 64Gb i have same messege. Help me please(

**Comment by sairuk** [comment]
deluge 2.0.3 seems to have become pretty flaky, I am still trying to track down the exact issue, sometimes it works OK other times not

**Comment by sairuk** [comment]
can you try out the reinstalling form the testing branch and let me know if this fixes your issues

**Comment by 4gordi** [comment]
i reinstall retronas from test branch on clean raspbian os and install only bittorrent, and have this problem too. Maybe you can explain me, retronas install and create folders by default in "/data/retronas/bittorrent/". Should I change the path settings in the web interface in deluge? Maybe i should change paths where i add a torrent file?

**Comment by 4gordi** [comment]
![image](https://github.com/danmons/retronas/assets/27728217/8f88db8b-20d1-476a-bd09-e92e0ccde752)

**Comment by sairuk** [comment]
the problem was that the (web) client couldn't find the configuration information so it would report an error because deluged was broken and had nowhere to download too.

a fresh install on my test vm installs ok now consistently

![image](https://github.com/danmons/retronas/assets/526372/0e92b8de-ab62-4a40-b894-87a806e56aa5)

you can have a look at the status of the deluge-web service with `systemctl status deluge-web.service` and see if there are any errors output

**Comment by 4gordi** [comment]
It's clear installing from testing branch

![image](https://github.com/danmons/retronas/assets/27728217/4cc095aa-b4a5-4902-9e1c-0b773d83b21c)

**Comment by sairuk** [comment]
interesting the same error is still present, that is a product issue and should be raised with deluge.

retronas installs deluge OK now, so i will close this issue
