### ISSUE TITLE
NeoGeo-CD Folder needed for MiSTer Share. N64 Folder (VERY EARLY STAGES)

### ISSUE THREAD

**Issue by davedoc1984** [danmons/retronas#340]
As the title suggests, need the MiSTer link for the NeoGeo-CD folder for the ISO's for that system. The Core requires a NeoGeo-CD Specific folder. Creating one manually on the Retronas MiSTer share doesn't get picked up by MiSTer FPGA.

**Comment by sairuk** [comment]
NeoGeo-CD was added in commit https://github.com/danmons/retronas/pull/336/commits/2147c6a7d4a84ee531390659239d2d5f7a3c26fb

neither NeoGeo-CD nor N64 appear in the main MiSTer_Distribution repo yet, so these can wait until they are officially supported.

if there is another repo we should be considering checking against, feel free to link it and reopen
