### ISSUE TITLE
Update Mister Cores Links

### ISSUE THREAD

**Issue by s3anami** [danmons/retronas#351]
Can you update the sym links to include n64 and other newer beta cores

**Comment by sairuk** [comment]
these features are available in the testing branch and will be rolled to main next merge

**Comment by s3anami** [comment]
n64 link isn't created even in test branch

**Comment by sairuk** [comment]
The data is there, check there isn't already a folder created by update_all if there is remove it and rerun updates

 ```
  - { src: "nintendo/nintendo64", last: "", mister: "N64", retropie: "", batocera: "n64", recalbox: "n64", retroarch: "Nintendo - Nintendo 64", ops2l: "", ps3netsrv: "", fspd: "", emuelec: "n64", smdb: "EverDrive 64 & 64drive SMDB.txt", freestation: "n64" }
 ```
