### ISSUE TITLE
Etherdfs and Dos Fat

### ISSUE THREAD

**Issue by aminta** [danmons/retronas#367]
I've carefully followed these guides https://github.com/danmons/retronas/wiki/FAT + https://github.com/danmons/retronas/wiki/EtherDFS and successfully mounted a 8TB  (fat32) image as dos:

This is my `etherdfs.service` status, is this a issue?

Because from my MS-DOS 6.22 (installed on a MiSTer) I can see the Retronas ethernet address, I can use the [etherdfs-client](https://github.com/BrianHoldsworth/etherdfs-client#etherdfs-client) addressing the MAC address of my raspberry and mapping "C" to "X" but when i type "X;" and" dir" on DOS it says "file not found"...

```
● etherdfs.service - EtherDFS lightweight file server for MS-DOS
     Loaded: loaded (/lib/systemd/system/etherdfs.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-10-16 20:12:08 BST; 16min ago
   Main PID: 544 (ethersrv-linux)
      Tasks: 1 (limit: 1599)
        CPU: 25ms
     CGroup: /system.slice/etherdfs.service
             └─544 /opt/retronas/bin/ethersrv-linux -f eth0 /storage/dos

Oct 16 20:12:08 raspberrypi4retronas systemd[1]: Started EtherDFS lightweight file server for MS-DOS.
Oct 16 20:15:23 raspberrypi4retronas systemd[1]: /lib/systemd/system/etherdfs.service:8: Unknown key name 'Umask' in section 'Service', ignoring.

```

**Comment by sairuk** [comment]
No, as it says it has ignored the invalid entry, it is something we should probably address to stop confusion though.

**Comment by danmons** [comment]
Can you verify `/storage/dos` is FAT? The output of `df -hT /storage/dos` in Linux will confirm. Similarly, `mount` will show all mounted volumes, and should list `/storage/dos` specifically. 

8TB is also very large for FAT. Maybe retry the process with 1TB as well, just to see what the effect is. (2TB is the upper bounds for FAT32 with default cluster size, although I'm not sure if that matters to EtherDFS). 

I'll attempt to rebuild and re-test some time this week on latest versions with an 8TB volume.

**Comment by aminta** [comment]
Ok, I've reset the previous one virtual hd and created a new virtual hd of 1TB.

**Comment by aminta** [comment]
Ok, this is the answer I've got from a member of MiSTer Fpga Forum, it seems sensible:

I'm not familiar with this particular software, but I'd guess from the programmer's description of EtherDFS that it won't work on anything other than real hardware with a real Ethernet card connected directly to a real, wired, Ethernet network.

Per the EtherDFS Read Me, EtherDFS works directly with Ethernet packets and doesn't use any higher level protocol.

AO486 doesn't emulate a network card. Instead, it uses PPP to transport higher-level protocols (IP, IPX, etc.) via an emulated serial link. Then, the MiSTer hard processor system at the other end of the PPP link places that traffic on the attached Ethernet or WiFi network.

So, from the EtherDFS client's perspective on AO486, there's no Ethernet card with which to interface. You'll need to use a different protocol. FTP would be the usual way to send files, but for a drive mount, your best option is going to be either SMB (LanMan/SAMBA) or IPX/SPX (Netware). I'm not sure if either of these play well with PPP.

Again, I'm not an expert, and I'd love to be proved wrong, but that's how I see it.

**Comment by sairuk** [comment]
As this is not a retronas issue i am closing this, if you find success in this down the line it would be great if you could let the project know in the discussions area
