### ISSUE TITLE
No more retronas / boot after I've tried to install BitTorrent

### ISSUE THREAD

**Issue by aminta** [danmons/retronas#369]
I had a retronas perfectly working on Raspberry 4 until tonight, when I've tried to install BitTorrent following this official instructions: https://github.com/danmons/retronas/wiki/BitTorrent.

Now Raspberry show boots sequence until the /boot command then no sign of life from it...

Each time I retry, the boot comes only until /boot command...

**Comment by sairuk** [comment]
Chances are your root partition is out of space, put the SD cad in another PC and clean up some space on the root partition

**Comment by aminta** [comment]
Ok thanks
