### ISSUE TITLE
hdparm.sh: line 10: syntax error near unexpected token ')'

### ISSUE THREAD

**Issue by tjanas** [danmons/retronas#371]
In the stable (main) branch of ansible/templates/install_hdparm/hdparm.sh.j2:
```
# check for config file
[ ! -f {{ retronas_path }}/config/hdparm-manager-drive) ] && exit 1
```

This results in the following in hdparm.sh:
```
# check for config file
[ ! -f /storage/config/hdparm-manager-drive) ] && exit 1
```

As a result, trying to select the drive results in a syntax error.

Removing the trailing parenthesis from the generated hdparam.sh fixes the issue

https://github.com/danmons/retronas/blob/master/ansible/templates/install_hdparm/hdparm.sh.j2#L10C11-L10C11

**Comment by sairuk** [comment]
thanks this is now addressed in testing
