### ISSUE TITLE
restart hdparm service on reboot

### ISSUE THREAD

**Issue by tjanas** [danmons/retronas#373]
I have installed and started the hdparm service, but when my retronas is rebooted, the service is not restarted; I have to manually enter the RetroNAS Main Menu -> Advanced -> hdparm -> Start

Can this service be (optionally) restarted on reboot?

https://github.com/danmons/retronas/discussions/332#discussioncomment-7549055_

**Comment by sairuk** [comment]
this service is run from a timer,, continue this discussion in the discussion area

**Comment by tjanas** [comment]
Fixed via https://github.com/danmons/retronas/commit/51329c158a0535ebc300651147ed922aa200e0f4
