### ISSUE TITLE
PS5 fpkg (*.pkg) files support for HB-Store

### ISSUE THREAD

**Issue by Gkiokan** [danmons/retronas#383]
The ps4 support was added already back then on this Request #177  
  
According to the latest Scene updates, the HB-Store is also available for Jailbroken PS5 Consoles.  
The latest [Release Version v1.4.1](https://github.com/Gkiokan/hb-store-cdn-cli-server/releases/tag/v1.4.1) does include the ps5 support and a big refactoring.

According to the [Issue Request](https://github.com/Gkiokan/hb-store-cdn-cli-server/issues/11) it is working for one of my users on the PS5.

**Comment by sairuk** [comment]
wont be on our radar for a while, much like switch and whatever they called the latest xbox

folks are welcome to do their own symlinks, it'll match up later on
