### ISSUE TITLE
GOG Offline Backup - Cannot select OS

### ISSUE THREAD

**Issue by Pontiac76** [danmons/retronas#384]
I'm not quite sure if the problem I've found with RetroNAS or if there's an update that has to happen for Gog Offline.

If I go into Tools, GOG, and try to select my OS, it relaunches the main RetroNAS setup as a child process.  

I noticed that when I'm in the menu itself, in another CLI I can see this process running
/bin/bash /opt/retronas/lib/script_runner.sh m-gogrepo

So I run it, and I get the same menu.  Cool.  But I run into the same problem where the RetroNAS main menu comes back up.

So digging deeper, I find https://github.com/sairuk/gogrepo and tried running that at the CLI both as root and as the pi user, and I'm being told about failing to load the cookies, but, going through retronas seems to at least get the md5sums on all my games.

Where's the actual config so I can manually work around the issue I seem to be having?

Edit: Digging one atoms depth deeper, I found that when I ran from the RetroNAS menu, the following command shows up

/bin/bash /opt/retronas/scripts/gogrepo_update.sh -skipknown -os windows mac

**Comment by Pontiac76** [comment]
After a someone decent sleep, and this particular MAC thing annoying me, I dug more into the code.

I went into /opt/retronas and started to look at the retronas.sh script.  At the top, there's a bunch of predefined variables, specifically _CONFIG.  Looking at that file I saw that there's a bunch of additional EXPORT variables defined.  Tracing through whats going on in my head, I figured that the pat works out to be /opt/retronas/ansible/retronas_vars.yml.  Getting into that, I see retronas_gog_os being set to "windows mac".  Yanked the "mac", deleted my manifest file, and restarted the update and I've obtained the result I wanted.

However, the "bug" still exists with the UI not allowing me to change the OS.

**Comment by sairuk** [comment]
Thanks for the detailed look, the gogrepo menus are broken at the moment, ever since i migrated to the new menus. it is known and is on my list of things. i'll look at fixing them today.

the file you want to look at is `retronas/config/menus/gogrepo.json` only the first menu is currently used. from here you can see on item 3 it is not of type `script` and command is a placeholder `TOOL_COMMAND`

it should look something like below, fwiw i need to confirm the below later today
```
            {
                "index":"03",
                "title": "Select OS",
                "description": "Change OS preferences",
                "id":"gog-os-input",
                "prompt": "",
                "type": "script",
                "group":"gogrepo",
                "command": "gogrepo_update"
            },
```

**Comment by Pontiac76** [comment]
Thanks.  I attempted to make the changes on my own, and I still end up in the recursive menus, even after I figured out "retronas -g".

I appreciate this effort.  I meant to write my own app that'd do this kind of thing years ago, but gave up when I found that I didn't have enough drive space across all of my machines.  Modern storage technology, GigE, a few TB of NAS storage, I'm quite happy with this so far.  Thanks again.

**Comment by sairuk** [comment]
this should be functional now (testing branch), could you please confirm

**Comment by Pontiac76** [comment]
Looks good.  I'm able to select the OS.

**Comment by sairuk** [comment]
closing this out based on the above
