### ISSUE TITLE
Is RetroNAS required or can I use TrueNAS or other NAS?

### ISSUE THREAD

**Issue by Sawtaytoes** [danmons/retronas#385]
I've gone through the docs a few times and don't understand how it works. It says in the docs that it works with the MiSTer FPGA, but it doesn't say how:
![image](https://github.com/danmons/retronas/assets/3948069/66f22ff0-f7d4-4bd9-b770-f9b4bb485f6c)

Is RetroNAS doing something special? Can you list in the docs the protocol you need to use to be compatible with these systems such as the MiSTer FPGA with a link to their setup docs?

From what I'm seeing in videos, this is a NAS with lots of protocols, but I'm not sure how the MiSTer is supposed to access it. In every video on the MiSTer, everyone's using microSD cards, not SMB or NFS shares, so I'm not sure how this is supposed to work just from the docs and some RetroRGB videos I saw.

**Comment by sairuk** [comment]
RetroNAS simplifies this installation for the users of RetroNAS, RetroNAS is not required for loading MiSTer data across a network.

MiSTer uses cifs (smb/samba), this is documented (at a minimum) in the playbook where it installs configuration and restarts the samba service pointing at our configured MiSTer directory.

if you want to setup a samba share on some other NAS product you can do so but refer to that products documentation.

Our documentation for MiSTer covers the MiSTer side of the configuration to connect to the samba share refer to https://github.com/danmons/retronas/wiki/MiSTer-FPGA#MiSTer-FPGA-configuration you can follow this and point it at your alt NAS product once your share is setup.

This repo and doco we have here is for the RetroNAS project, if you want to understand how to integrate MiSTer on a specific alt product please ask on their support channels.

**Comment by tjanas** [comment]
> everyone's using microSD cards, not SMB or NFS shares

https://www.retrorgb.com/introducing-retronas.html
