### ISSUE TITLE
Mister cifs mount

### ISSUE THREAD

**Issue by willoucom** [danmons/retronas#4]
Hello,

I noticed some errors in the wiki for the misterfpga configuration.

Is this ok if I paste the corrected text here ? (the wiki is in read only)

Thanks

**Comment by birdybro** [comment]
While on the topic...

https://github.com/danmons/retronas/wiki/MiSTer-FPGA#a-note-about-mister-updates

This section should mention the startup script that is located in `/media/fat/linux/_user-startup.sh`

I believe you just need to rename it to user-startup.sh and add a line to run the cifs mount script and it will always mount correctly. The only exception being linux updates, so some people store a backup of their user-startup.sh. Maybe some part of this could be automated with a health check for the mount, and then RetroNAS ssh's in to fix it if it's not working?

**Comment by danmons** [comment]
> Is this ok if I paste the corrected text here ? (the wiki is in read only)

Yes please, paste away.

**Comment by willoucom** [comment]
note: in mister, most scripts can use an ini file to configure themselves, since I think this is a better solution than editing shell scripts, here are the changes I suggest.

also, the local_dir directive changes the location of the mount point, I prefer to set it to "games" so I don't have to navigate to load the games.


----

Edit the following configuration lines in the `cifs_mount.ini` configuraton scripts.  You'll need to substitute in the right IP address and password.  You can do this either by editing the script elsewhere and copying it over, or SSH in and run

```
cd /media/fat/Scripts
nano cifs_mount.ini
```

Navigate with the arrow keys on your keyboard and edit as you wish.  When complete, press:
* `Control + x` to exit
* It will ask at the bottom of the screen : `Save modified buffer?`.  Press `y` for yes.
* It will ask at the bottom of the screen: `File Name to Write: cifs_mount.ini`. Press `enter` to confirm. 
* You will drop back to the command prompt with the file saved.

Use the following values inside your cifs_mount.ini file. For the "ipaddress" part below, substitute in your RetroNAS device's IP address.  The NetBIOS name `retrosmb` should work too, and is convenient if your RetroNAS device changes IP address due to DHCP. 

```
SERVER="ipaddress"
SHARE="mister"
USERNAME="pi"
PASSWORD="yourpipassword"
LOCAL_DIR="games"
WAIT_FOR_SERVER="true"
MOUNT_AT_BOOT="true"
```
Once saved, on reboot your MiSTer FPGA will take a few seconds to get an IP address from your DHCP server.  Once done, it should automatically mount your CIFS share.  (If not, you can press F12 at the main MiSTer menu, navigate to the "Scripts" folder and run the "mount_cifs.sh" script).

From there, navigate MiSTer cores as normal, and when loading ROM, ISO, BIN/CUE, VHD, etc files through the `F12` menus, the contents of your NAS should appear in MiSTer.

**Comment by sairuk** [comment]
The MiSTer FPGA page has now been updated to reflect these recommendation, thanks @willoucom 

https://github.com/danmons/retronas/wiki/MiSTer-FPGA
