### ISSUE TITLE
apt-key deprecated

### ISSUE THREAD

**Issue by KSzyDev** [danmons/retronas#41]
![retronas_error](https://user-images.githubusercontent.com/37033469/152627093-58d0f31f-de58-4b8c-9db7-417b8e9116b6.png)

Just tried to setup Cockpit through RetroNAS and ran into this error. I followed all the steps within the install guide multiple times, everything before that runs fine, but when it come to the key signing phase, I always get this error. 

Is there something I can be doing wrong?

Thanks

**Comment by danmons** [comment]
The deprecation warning is fine (I'll need to update this at some point, but that's not the error right now).  The error there is your system can't talk to the key server to download the key in question (needed to verify and install the package).

I'll do some more testing on a fresh install and see if I can replicate it.  In the meantime, please re-test in case it was an upstream outage with the keyserver.

**Comment by danmons** [comment]
Tested now from a clean Debian 11 VM and the cockpit install worked.

Can you test that you can reach the keyserver in a web browser?:
https://keyserver.ubuntu.com/

**Comment by KSzyDev** [comment]
I was able to view the keyserver in my web browser

**Comment by KSzyDev** [comment]
I am going to try another fresh install of RaspOS Lite 64bit now and see if there is a change.

**Comment by KSzyDev** [comment]
Still having the same issue with the keyserver, I even went as far as rebooting my router and modem to see if it would resolve, but nothing seemed to work for this error.

Thanks for your time.

**Comment by KSzyDev** [comment]
Was able to figure out what went wrong. My /etc/resolv.conf had some different setting for the DNS than what my network uses. I changed them to CloudFlare DNS and was able to finally get cockpit installed.

**Comment by danmons** [comment]
The key servers listen in non-http(s) ports which sometimes seem to cause problems for people behind strict firewalls. I'll migrate the key fetch to a standard file downloader, and then switch to the more modern way of handling APT keys.

**Comment by danmons** [comment]
This should be sorted now.  Key server method has been replaced by a deb package with the keys being installed locally, should prevent these warnings/failures.

If the issue persists, please open a new issue.
