### ISSUE TITLE
Cockpit doesn't install correctly for 32-bit or 64-bit raspberry pi os, pi 4gb?

### ISSUE THREAD

**Issue by VersatileNinja** [danmons/retronas#58]
I was able to get into retronas, but I noticed when I try to install cockpit, it will go through but at the very end it shows this very long red error message.

When I check services running, cockpit is not running. When I try to access the pi through the web browser ipaddress:9090, it doesn't work, because cockpit isn't working.

BUT if I install it manually  via: `sudo apt install cockpit', then it works! Why is that?

**Comment by sairuk** [comment]
Can you add the error to this issue to aide in troubleshooting?

**Comment by VersatileNinja** [comment]
I will record the error and post it tomorrow (maybe I can get a screenshot to share t0o), thanks in advance.

**Comment by sairuk** [comment]
Hi please also review this issue https://github.com/danmons/retronas/issues/8 to see if is related at all

**Comment by VersatileNinja** [comment]
![image](https://user-images.githubusercontent.com/38771551/153090798-c52f098b-ed78-46f6-a185-16ded03bd7dc.png)

I did a fresh install on my pi 4gb, 32-bit raspberry pi os. Afterwards, I enabled ssh using raspi-config, did not use a blank ssh file for example.

Now I go to install cockpit from the retronas interface, and I get the red error (see image provided).

I know that if I were to install cockpit manually outside of retronas, it will work, but I'd like to help you troubleshoot how to make installer work? I'm a raspberry pi novice, but glad to help where I can.

**Comment by sairuk** [comment]
This looks like you are having the same apt-key problem as mentioned in issue https://github.com/danmons/retronas/issues/41

**Comment by VersatileNinja** [comment]
Thanks for the tip. That did the trick and I fixed it by the following (for anyone in future curious what I did):

I did the following:
`sudo nano /etc/dhcpcd.conf`

Then added at the bottom for CloudFlare public DNS:
`static domain_name_servers=1.1.1.1 1.0.0.1`

Restart the service:
`sudo service dhcpcd restart`

Afterwards, went back into retronas and cockpit installed successfully! Not sure why it would install correctly outside of retronas even though I didn't change the DNS, but at least it works the way it is supposed to right now.

**Comment by torange** [comment]
Thank you @VersatileNinja for the solution. Had the same issue with fresh 64 bit RPi OS Lite install.

**Comment by danmons** [comment]
> This looks like you are having the same apt-key problem as mentioned in issue #41

I'll try and get a fix out for this soon.  I'm not sure why certain setups aren't able to resolve the key servers.  "works for me" on my stock RPiOS bullseye 64bit.

Fix will be to avoid the key servers and just grab the Debian signing keys via a dpkg file.

**Comment by sairuk** [comment]
I will reopen this while we are pending a fix so we have visibility on occurrence of this iss

**Comment by danmons** [comment]
Sorted this just now.  New method no longer uses "apt-key" nor points to keyservers listening on weird ports. 

Instead it grabs the .deb package containing the keys (with a couple of known working mirrors as fallback to each other) and installs that.  It's more compliant with the new APT key storing method, and should be more reliable for people either with poor DNS servers or restrictive firewalls.
