### ISSUE TITLE
Cockpit issue with large WD drive

### ISSUE THREAD

**Issue by danmons** [danmons/retronas#59]
Report from Twitter from a user who couldn't format and mount a large WD Elements 16TB drive via Cockpit.

Thread starts here, but we diverge into messages about half way:
https://twitter.com/lylotic/status/1490944794138673153

Only working solution was to "gdisk" the drive in Linux, format in Windows, then mount as NTFS via Cockpit, which appears to have worked.  Attempts to partition in cockpit produced errors, and mounting came back with "file too large" errors.

Inevitably that caused issues with non-POSIX ownership, however "uid=pi,gid=pi" custom mount options solved that.

[Edit] no it didn't. I'll need to test NTFS more.

Strangely, another WD user with a large disk has an issue here too:
https://github.com/danmons/retronas/issues/24

I'm unsure if the issue was the drive size, something WD are doing, something on the RPi side, or cockpit.  I'll try to make an upstream issue with cockpit at least to see if anyone there has seen this.  I don't have a USB disk large enough to simulate this for testing myself, nor any of the WD family of USB drives.

**Comment by danmons** [comment]
I've written a lengthy document and shared it with the user in question.  Guide takes them through partitioning/formatting in Windows, and editing /etc/fstab manually to mount the disk as an NTFS volume with `uid=pi,gid=pi` mount options for ntfs-3g (making it compatible with RetroNAS).

I'll await user feedback.  If it works, there's a problem with Cockpit, and I'll try to contact them.  If it fails, there's a problem with the RPi seeing large USB-attached WD drives specifically, which might mean chatting on the RPi forums to see if anyone else has the same issue.

**Comment by danmons** [comment]
First attempt did not work.  Drive was partitioned under  Windows as NTFS, mounted under Linux with `uid=pi,gid=pi`.  Everything worked fine, including writing files on the command line to the volume.

As soon as Ansible attempted to write to the file, "Errno 5 Input/output error" errors flowed for every operation.

On mount, the RPi says in dmesg: "Very big device.  Trying to use READ CAPACITY(16)".  But everything seems OK after that with no IO errors on any normal CLI operations. 

There were errors too about GPT CRC32 entries not matching when partitioned in Windows.  Those errors don't exist when partitioned in Linux, however the same Ansible IO errors are reported.

I don't think the device is faulty.  I do think there's an issue with either something WD are doing, or very large disks on the RPi hardware/firmware.

Next test is to wipefs the device and put a filesystem direct on /dev/sda (no partitions) and see what happens.

**Comment by danmons** [comment]
Previous testing with GPT partitioning and XFS failed (so it wasn't isolated to the NTFS format). 

wipefs to blow away all partitions and then mkfs.btrfs right on the raw disk device (/dev/sda on the RPi, no partitions so no /dev/sda1) worked.  The filesystem mounted, RetroNAS installed and Ansible ran as expected on that volume/path.  

I'm unsure if it's the GPT partitioning on that big disk that's the problem, or something else specific to large disks, or something specific to Western Digital devices.  

However that is a work-around for now, but sadly requires quite a lot of dangerous and advanced command line usage.  Not exactly user-friendly.

I'm going to take a look at webmin and see what it offers for disk partitioning/formatting.  If this crops up again, I'll need another willing volunteer to make it work (the current tester has a working system and is understandably unwilling to blast it all and start again).

At some point I also want to try LVM (with the physical volume both directly on the raw device and inside a GPT partition).  But I didn't want to over-complicate this particular round of testing.  BtrFS allows the user to JBOD if they wish (they mentioned wanted to grow the volume later), or just happily work as-is for now.

More testing required either way.

**Comment by danmons** [comment]
Almost identical issue described here. Drive works fine on a desktop system, but is extremely fussy in an RPi4:

https://forum.storj.io/t/raspberry-pi-4-doesnt-power-on-wd-usb3-drive/6044

**Comment by birdybro** [comment]
I have a [WD Elements 14TB desktop external](https://www.amazon.com/gp/product/B07YD3G568/) and I don't have this issue.

**Comment by danmons** [comment]
> I have a [WD Elements 14TB desktop external](https://www.amazon.com/gp/product/B07YD3G568/) and I don't have this issue.

Previous use was on an RPi4 on 32bit RPiOS, and the error was during the mount operation within cockpit.

Does that match your setup?

**Comment by birdybro** [comment]
RPi4 with 5.10.92-v8+ aarch64 linux (RPiOS). So no, not 32-bit.

**Comment by danmons** [comment]
A third related issue posted here:
https://github.com/danmons/retronas/issues/104

I've posted on the RPi forums documenting the issue.  Waiting for the post to be approved and then hoping it gets some eyes on:
https://forums.raspberrypi.com/viewtopic.php?t=330024

I feel like this is an RPi specific issue.  I will try to replicate this in a VM.  I can over-allocate a virtual disk using dd's "seek" parameter to create a disk larger than my local file system, and see if the issue exists there too.  Might not be a viable test though, but we'll see.

**Comment by danmons** [comment]
Suggestion back from RPi forums was to ensure that 64bit RPiOS is used for large disks.  Could I ask anyone with a large disk willing to test to try out RPiOS 64bit and report back.

**Comment by sairuk** [comment]
I would keep in mind it doesn't appear raspios gnu apps are compiled with large file support enabled which may have some impact, as per issue https://github.com/danmons/retronas/issues/112 a large enough number was able to prevent the `shuf` command from determining a random number that was expected to be used later to read a drive sector

just a note say that the fdisk/mount commands may be running into similar issues see https://www.gnu.org/software/coreutils/faq/coreutils-faq.html

this lack of lfs support in the toolset also affects 64bit raspios based on the live image i tried

**Comment by sairuk** [comment]
Is there still an issue here? I think the wiki should be updated with the findings about the 64bit OS (if it hasn't already) and we should close this off otherwise this is just going to end up being one of those tickets that never close

**Comment by danmons** [comment]
Yup, let's close it off.  New reports can come in as new issues, and I'll update the wiki.
