### ISSUE TITLE
Netatalk 2 bug after running install a 2nd time

### ISSUE THREAD

**Issue by birdybro** [danmons/retronas#7]
Netatalk2 installation after mounting usb hdd storage, changing top level directory, and then changing hostname resulted in this error:

![image](https://user-images.githubusercontent.com/16388068/151919177-dda7b3cf-45f7-4449-be6d-db30116f0b78.png)

**Comment by birdybro** [comment]
Proftpd also had a result of failing upon reconfiguration.

![image](https://user-images.githubusercontent.com/16388068/151920373-1598c70f-0c22-474a-84be-fc4eafcea67e.png)

```
pi@retronas:/opt/retronas $ sudo systemctl status proftpd.service
sudo: unable to resolve host retronas: Name or service not known
● proftpd.service - ProFTPD FTP Server
     Loaded: loaded (/lib/systemd/system/proftpd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-02-01 06:03:02 GMT; 47s ago
    Process: 42314 ExecStartPre=/usr/sbin/proftpd --configtest -c $CONFIG_FILE (code=exited, status=1/FAILURE)
        CPU: 31ms

Feb 01 06:03:02 retronas systemd[1]: Starting ProFTPD FTP Server...
Feb 01 06:03:02 retronas proftpd[42314]: Checking syntax of configuration file
Feb 01 06:03:02 retronas proftpd[42314]: 2022-02-01 06:03:02,247 retronas proftpd[42314]: warning: unable to determine IP address of 'retronas'
Feb 01 06:03:02 retronas proftpd[42314]: 2022-02-01 06:03:02,247 retronas proftpd[42314]: error: no valid servers configured
Feb 01 06:03:02 retronas proftpd[42314]: 2022-02-01 06:03:02,247 retronas proftpd[42314]: fatal: error processing configuration file '/etc/proftpd/proftpd.conf'
Feb 01 06:03:02 retronas systemd[1]: proftpd.service: Control process exited, code=exited, status=1/FAILURE
Feb 01 06:03:02 retronas systemd[1]: proftpd.service: Failed with result 'exit-code'.
Feb 01 06:03:02 retronas systemd[1]: Failed to start ProFTPD FTP Server.
```

**Comment by danmons** [comment]
In both cases, did you change the configuration via 

Configuration -> Configure RetroNAS top level directory

And then re-run those installers after that?

**Comment by idledk** [comment]
The first issue should only be able to occur if you have some soft of update script that also forces updates of packages that have been put on hold.
The error might be that you have also tried installing netatalk3. netatalk2 and netatalk3 cannot co-exist.

**Comment by danmons** [comment]
> The first issue should only be able to occur if you have some soft of update script that also forces updates of packages that have been put on hold.

This is very likely the culprit.  Netatalk2 is currently a binary package stolen from an earlier version of Debian, and then marked for hold so the current Netatalk3 package in-repo doesn't overwrite it.

I'll check that tomorrow and add an unhold/rehold to solve it being installed over the top of itself.  Long term I'm removing this method for a source fork of a new Netatalk2.x build that's just recently gone stable by the author, and will be a better fit for RetroNAS.

> The error might be that you have also tried installing netatalk3. netatalk2 and netatalk3 cannot co-exist.
This too, however choosing one will uninstall the other.  I think the first point is correct - installing Netatalk2 over itself will probably break at the moment, and that's a RetroNAS bug I think I can fix.

**Comment by birdybro** [comment]
> In both cases, did you change the configuration via
> 
> Configuration -> Configure RetroNAS top level directory
> 
> And then re-run those installers after that?
> 

Yes.

> Also the config gets dropped in a separate file, located in /etc/proftpd/conf.d/retronas.conf
> 
> Verify that the directory listed in that config file is the same as your RetroNAS top level directory, and that the permissions on the directory are correct.

It all looks correct to me, user pi, group pi, and all references to the path is /storage. the `ServerName` is RetroNAS however, which is the "pretty name", but I have my doubts that this matters. It might though.

Thanks! I am prone to breaking things, so figured I'd help beta test it out a bit. :)

**Comment by danmons** [comment]
Very much appreciated!

I'll check in to this later on today.  I have a fix in mind for the Netatalk2 stuff, but I'll need to dig into ProFTPd.

**Comment by danmons** [comment]
ProFTPd fix committed.  The offending module in ProFTPd was "mod_unique_id.c".  It's used for virtual host lookups, and breaks if it can't find a matching hostname to DNS entry in either your network's DNS server or /etc/hosts.

I'm not using virtual hosts in FTP, so I don't need the feature.  I told Ansible to remove the item and force bind FTP to 0.0.0.0

Appears to be working now.  Please re-test and let me know how you go.

**Comment by birdybro** [comment]
Yup, everything seems to be working fine now! Thank you!
