### ISSUE TITLE
Getting errors can't install Need Help 

### ISSUE THREAD

**Issue by SammyC65** [danmons/retronas#75]
Ive been trying for 3 days  to install Retronas and getting the same error 
when I get to the line where I have to put in chmod a+x ./install_ retronas.sh says it can't find the file does not exist 
says above the previous line ECHO installation failed check previous messages

**Comment by sairuk** [comment]
Please let us know more details about where are attempting to install RetroNAS.

Currently while we are in the alpha stages Debian 11 is the target platform, preferably on a Raspberry PI 

Please post the output of the below commands as the user you are attempting to install RetroNAS as

The distro you are running
```
$ cat /etc/os-release
```

The user you are downloading the install_retronas.sh script as
```
$ whoami
```

The contents of the users home directory
```
$ ls -la $HOME
```

Assuming the script is in the users home directory
```
ls -la $HOME/install_retronas.sh
```

Check for an existing and/or partial installation
```
ls -la /opt/retronas/.git/config
```

Additionally please provide the full output of of the installation commands so we can assist you further.

**Comment by SammyC65** [comment]
I am trying to install on Rasperry Pi 4 im going step by step 
1. login in on Pi 
2. Sudo passed root 
3. Sudo raspi config 
4. change to retronas and enable SSH reboot 
5. login as Root 
6. put in this linecurl -O https://raw.githubusercontent.com/danmons/retronas/main/install_retronas.sh
7. then try chmod a+x ./install_retronas.sh 
8. can never find the file

**Comment by sairuk** [comment]
You can help us troubleshoot your issue by providing the output of the commands requested above so we have a good view of the current state of your system, thanks.

I have just clean installed on an RPI4 and it worked as expected

additionally what is the output of 

```
$ which curl
```

**Comment by SammyC65** [comment]
Good News it worked now trying to open up IP address page with 9090 at the end but can't seem to get it working just keeps searching for it when I open it up in google chrome

**Comment by SammyC65** [comment]
Good News I have all up and running through my Mac M1 so where would I find the retronas network on it

**Comment by sairuk** [comment]
Good to hear you have successfully installed RetroNAS,this issue will be closed.

For usage information see the wiki located here https://github.com/danmons/retronas/wiki

**Comment by SammyC65** [comment]
Well im having the same issue again I had to reinstall 
curl -O https://raw.githubusercontent.com/danmons/retronas/main/install_retronas.sh 
fails to install again
