### ISSUE TITLE
FSP server is not write enabled

### ISSUE THREAD

**Issue by Extrems** [danmons/retronas#79]
To support future development, there should be a `swiss` directory under the server's home directory, and it should contain the following blank files:

- `.FSP_OK_ADD`
- `.FSP_OK_DEL`
- `.FSP_OK_MKDIR`
- `.FSP_OK_RENAME`

These may be in the home directory instead if security is not a concern, while leaving the creation of the `swiss` directory to Swiss.

_Originally posted by @Extrems in https://github.com/danmons/retronas/discussions/74#discussioncomment-2145850_

**Comment by danmons** [comment]
New config now does the following:

* Sets FSP home folder as {{retronas_path}}/gamecube/swiss
* Below that creates the following folders:
  * `swiss` (as requested)
  * `tmp` (needed for large writes apparently?  Set matching in fspd.conf as per man page)
  * `games` symlink to `../../roms/nintendo/gamecube/iso`
  * The four empty dotfiles requested above
  
 Testing with the command line "fput" command like such:
 
 ```
 date > testfile.txt
 FSP_HOST=XXX.XXX.XXX.XXX FSP_PORT=2121 fput testfile.txt
 ```
 
Sees the file dropped in to the FSP home directory, mode 0644.  (Previously this test failed with a write permission error, now working with the above config).
 
Changes committed and now public.

**Comment by Extrems** [comment]
If you create the `swiss` directory ahead of time while creating the `.FSP` files in the home directory, the `.FSP` files also need to be in the `swiss` directory.

**Comment by danmons** [comment]
Changes pushed to create the dotfiles in both the top level and `swiss` dir.

**Comment by sairuk** [comment]
Does this mean we can close this issue off or do we need confirmation from @Extrems of our deployment?
