### ISSUE TITLE
Cockpit & Mister FPGA Install Fails

### ISSUE THREAD

**Issue by totallymaxed** [danmons/retronas#8]
After a fresh install of RetroNAS I see this error when I enable Cockpit;

TASK [Cockpit - Install from repo] *****************************************************************************
client_loop: send disconnect: Broken pipe

I also see the same error when I enable Mister FPGA too.

I have seen this on two different installs now.

Andy

**Comment by danmons** [comment]
> client_loop: send disconnect: Broken pipe

This is a network level error - your connection to your remote system (whatever RetroNAS is installed on) is dropping.  Looks like you're SSHed in, and the SSH session dropped?

How are you physically connected?  WiFi or network cable?

**Comment by totallymaxed** [comment]
> 



> > client_loop: send disconnect: Broken pipe
> 
> This is a network level error - your connection to your remote system (whatever RetroNAS is installed on) is dropping. Looks like you're SSHed in, and the SSH session dropped?
> 
> How are you physically connected? WiFi or network cable?

The installation is on a Pi Zero W and the connection is over Wifi

**Comment by danmons** [comment]
From the command line, you should be able to run `sudo raspi-config` , and then navigate to "2 Interface Options" and inside that menu find the tool to permanently enable SSH.  (This is a Raspberry Pi OS provided tool, not mine). 

This will set it to start via systemd, and should be stable, even over WiFi (assuming your WiFi signal strength is OK).

**Comment by sairuk** [comment]
I am going to close this issue for now, comments have have gone stale, safe to assume if it was still an issue we would've heard back by now. Reopen if necessary
