### ISSUE TITLE
SMDB Tool appears to have incorrect output file for AtariLynx

### ISSUE THREAD

**Issue by citizen-why** [danmons/retronas#98]
The Atari Lynx SMBD pack seems to point to Colecovision for its output instead of pointing to Atari Lynx

![image](https://user-images.githubusercontent.com/99519679/153777966-e46ff624-a330-44c3-87f3-c50f4b4e411c.png)

**Comment by sairuk** [comment]
Thanks for the report coleco had the wrong SMDB option listed,

i've updated the template. you'll need to reinstall the feature to make out the updated script

**Comment by citizen-why** [comment]
Great - this is the only one that looked to be at issue during my most
recent run

**Comment by sairuk** [comment]
Closing this issue, please reopen if you notice anything further
